In [ ]:
import json
import glob

def raw_data_cordination(text):
    raw_data['valid_line'][n_vl]['words'].append({
        'quad': {
            'x1': result_clean[n]['value']['points'][0][0],
            'y1': result_clean[n]['value']['points'][0][1],
            'x2': result_clean[n]['value']['points'][1][0],
            'y2': result_clean[n]['value']['points'][1][1],
            'x3': result_clean[n]['value']['points'][2][0],
            'y3': result_clean[n]['value']['points'][2][1],
            'x4': result_clean[n]['value']['points'][3][0],
            'y4': result_clean[n]['value']['points'][3][1]
        },
        'is_key': 0,
        'row_id': result_clean[n+1]['value']['text'][0],
        'text': text
    })
def raw_data_append_words(category):
    raw_data['valid_line'].append({'words':[], 'category':category,
                                   'group_id':result_clean[n+1]['value']['text'][0],'sub_group_id':0})

In [ ]:
dirlist = [f for f in glob.glob("label_studio/*.json")]
for path in dirlist:
    label_file = open(path)
    label_data = json.load(label_file)
    image_id = label_data['id']
    result = label_data['annotations'][0]['result']
    result_clean = []# ohne Duplikation bzw. liste mit (Text)
    for i in range(len(result)):
        if 'text' in result[i]['value']:
            result_clean.append(result[i])
    for i in result_clean:
        w = i["original_width"]
        h = i["original_height"]
        for j in i['value']['points']:
            j[0] = int(round(j[0]*w/100))
            j[1] = int(round(j[1]*h/100))

    try:
        directory = "dataset_all/" + str(image_id) + ".json"
        print(str(image_id) + ":")
        raw = open(directory)


    except:
        print("No "+directory+" exist!")
        continue
    raw_data = json.load(raw)
    #print(raw_data)
    raw_data['meta']['image_size']['width'], raw_data['meta']['image_size']['height'] = result_clean[0]['original_width'], result_clean[0]['original_height']
    menu = raw_data['gt_parse']['menu']
    subtotal = raw_data['gt_parse']['sub_total']
    total = raw_data['gt_parse']['total']
    raw_data['ROI']['x1']=0;raw_data['ROI']['y1']=0;raw_data['ROI']['x2']=w;raw_data['ROI']['y2']=0;
    raw_data['ROI']['x3']=w;raw_data['ROI']['y3']=h;raw_data['ROI']['x4']=0;raw_data['ROI']['y4']=h;
    n_vl = 0 # the number of each valid_line
    for i in menu:
        nm = i['nm'].split(" ") # name of Pizza

        for j in nm:
            for n in range(len(result_clean)): #result_clean gibt es in Json aus LabelStudio
                if j == result_clean[n]['value']['text'][0]:
                    raw_data_append_words(category="menu.nm")
                    raw_data_cordination(j)
                    n_vl+=1
                    print("name = ",j)
                    result_clean.pop(n) # we use this code for delete duplicates

                    break

    cnt = i['cnt']
    for n in range(len(result_clean)):
        if cnt == result_clean[n]['value']['text'][0] and result_clean[n]["from_name"] == "transcription":
            raw_data_append_words(category="menu.cnt")
            raw_data_cordination(cnt)
            n_vl+=1
            print("count = ",cnt)
            result_clean.pop(n)
            break

#get the price of pizza


    price = i['price'].split(" ")[0]
    print(price)
    for n in range(len(result_clean)):
        if price == result_clean[n]['value']['text'][0]:
            raw_data_append_words(category="menu.price")
            raw_data_cordination(price)
            n_vl+=1
            print("price = ",price)
            result_clean.pop(n)
            break

#get the size of pizza


    if "etc" in i.keys():
        etc = i["etc"]
        for n in range(len(result_clean)):
            if etc == result_clean[n]['value']['text'][0]:
                raw_data_append_words(category="menu.etc")
                raw_data_cordination(etc)
                n_vl+=1
                print("size = ",etc)
                result_clean.pop(n)
                break
    sub_total_value = subtotal["subtotal_price"]

    for n in range(len(result_clean)):
        if "Netto" == result_clean[n]['value']['text'][0]:
                    raw_data_append_words(category="subtotal.subtotal_price")
                    raw_data_cordination("Netto")
                    n_vl+=1
                    print("Netto(sub_total_price) = ",sub_total_value)
                    result_clean.pop(n)
                    break

    total_price_value = total["total_price"]

    for n in range(len(result_clean)):
        if "Gesamt" == result_clean[n]['value']['text'][0]:
                    raw_data_append_words("total.total_price")
                    raw_data_cordination("Gesamt")
                    n_vl+=1
                    print("Gesamt(total_price) = ",total_price_value)
                    result_clean.pop(n)
                    break
    if "creditcardprice" in total.keys():
        creditcardprice_value =  total["creditcardprice"]
        for n in range(len(result_clean)):
                if creditcardprice_value == result_clean[n]['value']['text'][0]:
                        raw_data_append_words("total.creditcardprice")
                        raw_data_cordination(creditcardprice_value)
                        n_vl+=1
                        print("total_credit = ",creditcardprice_value)
                        result_clean.pop(n)
                        break
    if "creditcardprice" in total.keys():
        creditcardprice_value =  total["creditcardprice"]
        for n in range(len(result_clean)):
            if "EC"  == result_clean[n]['value']['text'][0]:
                raw_data_append_words("total.creditcardprice")
                raw_data_cordination("EC")
                n_vl+=1
                print("total_credit(EC) = ",creditcardprice_value)
                result_clean.pop(n)
                break

        for n in range(len(result_clean)):
            if "Karte"  == result_clean[n]['value']['text'][0]:
                raw_data_append_words("total.creditcardprice")
                raw_data_cordination("Karte")
                n_vl+=1
                print("total_credit(Karte) = ",creditcardprice_value)
                result_clean.pop(n)
                break
    if "creditcardprice" in total.keys():
        creditcardprice_value =  total["creditcardprice"]
        for n in range(len(result_clean)):
            if "Klarna" == result_clean[n]['value']['text'][0]:
                raw_data_append_words("total.creditcardprice")
                raw_data_cordination("Klarna")
                n_vl+=1
                print("total_credit(Klarna) = ",creditcardprice_value)
                result_clean.pop(n)
                break
    if "creditcardprice" in total.keys():
        creditcardprice_value =  total["creditcardprice"]
        for n in range(len(result_clean)):
            if "PayPal" == result_clean[n]['value']['text'][0]:
                raw_data_append_words("total.creditcardprice")
                raw_data_cordination("PayPal")
                n_vl+=1
                print("total_credit(PayPal) = ",creditcardprice_value)
                result_clean.pop(n)
                break
    if "creditcardprice" in total.keys():
        creditcardprice_value =  total["creditcardprice"]
        for n in range(len(result_clean)):
            if "ApplePay" == result_clean[n]['value']['text'][0]:
                raw_data_append_words("total.creditcardprice")
                raw_data_cordination("ApplePay")
                n_vl+=1
                print("total_credit(ApplePay) = ",creditcardprice_value)
                result_clean.pop(n)
                break
    if "creditcardprice" in total.keys():
        creditcardprice_value =  total["creditcardprice"]
        for n in range(len(result_clean)):
            if creditcardprice_value == result_clean[n]['value']['text'][0]:
                raw_data_append_words("total.creditcardprice")
                raw_data_cordination(creditcardprice_value)
                n_vl+=1
                print("total_credit = ",creditcardprice_value)
                result_clean.pop(n)
                break
    if "cashprice" in total.keys():
        cashprice_value = total["cashprice"]
        for n in range(len(result_clean)):
            if cashprice_value == result_clean[n]['value']['text'][0]:
                raw_data_append_words("total.cashprice")
                raw_data_cordination(cashprice_value)
                n_vl+=1
                print("cashprice(Bar) = ",cashprice_value)
                result_clean.pop(n)
                break
    print(raw_data)

    final_json = json.dumps(raw_data)
    final_dir = "final_labels/"+str(image_id) +".json"
    with open(final_dir, "w") as outfile:
        outfile.write(final_json)
    #outfile = open(final_dir, 'w')
    #outfile.write(final_json)
    #outfile.close()

100:
name =  Calzini
name =  Schinken
name =  Paprika
name =  250ml
name =  Red
name =  Bull
count =  1
2,09
price =  2,09
Netto(sub_total_price) =  5,57
Gesamt(total_price) =  6,19
total_credit =  6,19
total_credit(EC) =  6,19
total_credit(Karte) =  6,19
total_credit =  6,19
{'gt_parse': {'menu': [{'nm': 'Calzini Schinken Paprika', 'cnt': '1', 'price': '3,85'}, {'nm': '250ml Red Bull', 'cnt': '1', 'price': '2,09'}], 'sub_total': {'subtotal_price': '5,57'}, 'total': {'total_price': '6,19', 'creditcardprice': '6,19'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 100, 'image_size': {'width': 560, 'height': 376}}, 'valid_line': [{'words': [{'quad': {'x1': 64, 'y1': 127, 'x2': 154, 'y2': 132, 'x3': 154, 'y3': 159, 'x4': 64, 'y4': 153}, 'is_key': 0, 'row_id': '1', 'text': 'Calzini'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 164, 'y1': 132, 'x2': 262, 'y2': 137, 'x3': 262, 'y3': 162, 'x4': 162, 'y4': 159}, 'is_key': 0, 'row_id': '1', 'text': 'Schinken'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 272, 'y1': 136, 'x2': 354, 'y2': 137, 'x3': 356, 'y3': 167, 'x4': 270, 'y4': 165}, 'is_key': 0, 'row_id': '1', 'text': 'Paprika'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 39, 'y1': 151, 'x2': 106, 'y2': 156, 'x3': 105, 'y3': 182, 'x4': 39, 'y4': 177}, 'is_key': 0, 'row_id': '2', 'text': '250ml'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 112, 'y1': 156, 'x2': 155, 'y2': 157, 'x3': 155, 'y3': 183, 'x4': 112, 'y4': 183}, 'is_key': 0, 'row_id': '2', 'text': 'Red'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 162, 'y1': 158, 'x2': 217, 'y2': 161, 'x3': 214, 'y3': 186, 'x4': 163, 'y4': 184}, 'is_key': 0, 'row_id': '2', 'text': 'Bull'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 15, 'y1': 129, 'x2': 32, 'y2': 129, 'x3': 32, 'y3': 152, 'x4': 17, 'y4': 152}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 421, 'y1': 165, 'x2': 477, 'y2': 163, 'x3': 477, 'y3': 189, 'x4': 422, 'y4': 190}, 'is_key': 0, 'row_id': '2', 'text': '2,09'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 10, 'y1': 223, 'x2': 80, 'y2': 227, 'x3': 80, 'y3': 251, 'x4': 8, 'y4': 247}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 5, 'y1': 247, 'x2': 92, 'y2': 251, 'x3': 93, 'y3': 277, 'x4': 7, 'y4': 275}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 430, 'y1': 259, 'x2': 491, 'y2': 261, 'x3': 491, 'y3': 287, 'x4': 433, 'y4': 287}, 'is_key': 0, 'row_id': '4', 'text': '6,19'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 6, 'y1': 297, 'x2': 37, 'y2': 296, 'x3': 37, 'y3': 325, 'x4': 7, 'y4': 326}, 'is_key': 0, 'row_id': '5', 'text': 'EC'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 43, 'y1': 297, 'x2': 113, 'y2': 301, 'x3': 113, 'y3': 328, 'x4': 44, 'y4': 325}, 'is_key': 0, 'row_id': '5', 'text': 'Karte'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 433, 'y1': 303, 'x2': 490, 'y2': 305, 'x3': 492, 'y3': 336, 'x4': 434, 'y4': 339}, 'is_key': 0, 'row_id': '5', 'text': '6,19'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 560, 'y2': 0, 'x3': 560, 'y3': 376, 'x4': 0, 'y4': 376}}
10:
name =  Pan
name =  Funghi
name =  250ml
name =  Red
name =  Bull
count =  1
2,09
price =  2,09
Netto(sub_total_price) =  8,37
Gesamt(total_price) =  9,19
{'gt_parse': {'menu': [{'nm': 'Pan Funghi', 'cnt': '1', 'price': '6,85', 'etc': '25'}, {'nm': '250ml Red Bull', 'cnt': '1', 'price': '2,09'}], 'sub_total': {'subtotal_price': '8,37'}, 'total': {'total_price': '9,19'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 10, 'image_size': {'width': 719, 'height': 595}}, 'valid_line': [{'words': [{'quad': {'x1': 152, 'y1': 193, 'x2': 95, 'y2': 192, 'x3': 92, 'y3': 231, 'x4': 149, 'y4': 234}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 263, 'y1': 193, 'x2': 160, 'y2': 194, 'x3': 156, 'y3': 234, 'x4': 263, 'y4': 235}, 'is_key': 0, 'row_id': '1', 'text': 'Funghi'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 130, 'y1': 282, 'x2': 47, 'y2': 277, 'x3': 47, 'y3': 319, 'x4': 130, 'y4': 326}, 'is_key': 0, 'row_id': '2', 'text': '250ml'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 198, 'y1': 285, 'x2': 145, 'y2': 287, 'x3': 140, 'y3': 326, 'x4': 201, 'y4': 326}, 'is_key': 0, 'row_id': '2', 'text': 'Red'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 277, 'y1': 291, 'x2': 205, 'y2': 292, 'x3': 206, 'y3': 330, 'x4': 280, 'y4': 325}, 'is_key': 0, 'row_id': '2', 'text': 'Bull'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 45, 'y1': 182, 'x2': 13, 'y2': 181, 'x3': 10, 'y3': 223, 'x4': 40, 'y4': 224}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 625, 'y1': 292, 'x2': 546, 'y2': 291, 'x3': 546, 'y3': 332, 'x4': 627, 'y4': 332}, 'is_key': 0, 'row_id': '2', 'text': '2,09'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 113, 'y1': 376, 'x2': 15, 'y2': 372, 'x3': 15, 'y3': 416, 'x4': 112, 'y4': 416}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 15, 'y1': 450, 'x2': 129, 'y2': 454, 'x3': 130, 'y3': 417, 'x4': 13, 'y4': 416}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 719, 'y2': 0, 'x3': 719, 'y3': 595, 'x4': 0, 'y4': 595}}
11:
name =  Pan
name =  Prosciutto
name =  e
name =  Funghi
name =  1L
name =  Mezzo
name =  Mix
count =  1
3,29
price =  3,29
Netto(sub_total_price) =  16,13
Gesamt(total_price) =  17,62
total_credit =  17,62
total_credit(PayPal) =  17,62
total_credit =  17,62
{'gt_parse': {'menu': [{'nm': 'Pan Prosciutto e Funghi', 'cnt': '1', 'price': '14,08', 'etc': '28'}, {'nm': '1L Mezzo Mix', 'cnt': '1', 'price': '3,29'}], 'sub_total': {'subtotal_price': '16,13'}, 'total': {'total_price': '17,62', 'creditcardprice': '17,62'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 11, 'image_size': {'width': 1280, 'height': 948}}, 'valid_line': [{'words': [{'quad': {'x1': 275, 'y1': 309, 'x2': 175, 'y2': 302, 'x3': 179, 'y3': 367, 'x4': 272, 'y4': 363}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 579, 'y1': 304, 'x2': 289, 'y2': 302, 'x3': 290, 'y3': 368, 'x4': 587, 'y4': 370}, 'is_key': 0, 'row_id': '1', 'text': 'Prosciutto'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 638, 'y1': 302, 'x2': 591, 'y2': 302, 'x3': 596, 'y3': 372, 'x4': 633, 'y4': 367}, 'is_key': 0, 'row_id': '1', 'text': 'e'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 819, 'y1': 310, 'x2': 657, 'y2': 305, 'x3': 653, 'y3': 373, 'x4': 825, 'y4': 376}, 'is_key': 0, 'row_id': '1', 'text': 'Funghi'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 151, 'y1': 471, 'x2': 94, 'y2': 472, 'x3': 92, 'y3': 527, 'x4': 161, 'y4': 528}, 'is_key': 0, 'row_id': '2', 'text': '1L'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 324, 'y1': 461, 'x2': 176, 'y2': 470, 'x3': 173, 'y3': 529, 'x4': 329, 'y4': 527}, 'is_key': 0, 'row_id': '2', 'text': 'Mezzo'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 441, 'y1': 466, 'x2': 342, 'y2': 462, 'x3': 341, 'y3': 528, 'x4': 443, 'y4': 525}, 'is_key': 0, 'row_id': '2', 'text': 'Mix'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 82, 'y1': 299, 'x2': 20, 'y2': 300, 'x3': 23, 'y3': 366, 'x4': 73, 'y4': 363}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1094, 'y1': 462, 'x2': 957, 'y2': 458, 'x3': 963, 'y3': 530, 'x4': 1103, 'y4': 524}, 'is_key': 0, 'row_id': '2', 'text': '3,29'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 196, 'y1': 627, 'x2': 20, 'y2': 618, 'x3': 23, 'y3': 696, 'x4': 198, 'y4': 686}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 16, 'y1': 744, 'x2': 223, 'y2': 739, 'x3': 220, 'y3': 687, 'x4': 18, 'y4': 694}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1127, 'y1': 753, 'x2': 962, 'y2': 751, 'x3': 963, 'y3': 683, 'x4': 1132, 'y4': 690}, 'is_key': 0, 'row_id': '4', 'text': '17,62'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 220, 'y1': 851, 'x2': 16, 'y2': 862, 'x3': 19, 'y3': 796, 'x4': 213, 'y4': 791}, 'is_key': 0, 'row_id': '5', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1122, 'y1': 781, 'x2': 970, 'y2': 786, 'x3': 974, 'y3': 847, 'x4': 1123, 'y4': 847}, 'is_key': 0, 'row_id': '5', 'text': '17,62'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 948, 'x4': 0, 'y4': 948}}
12:
name =  Pan
name =  Margherita
count =  1
14,78
price =  14,78
size =  32
Netto(sub_total_price) =  13,81
Gesamt(total_price) =  14,78
cashprice(Bar) =  14,78
{'gt_parse': {'menu': [{'nm': 'Pan Margherita', 'cnt': '1', 'price': '14,78', 'etc': '32'}], 'sub_total': {'subtotal_price': '13,81'}, 'total': {'total_price': '14,78', 'cashprice': '14,78'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 12, 'image_size': {'width': 1280, 'height': 887}}, 'valid_line': [{'words': [{'quad': {'x1': 252, 'y1': 338, 'x2': 163, 'y2': 333, 'x3': 165, 'y3': 396, 'x4': 256, 'y4': 394}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 585, 'y1': 333, 'x2': 272, 'y2': 334, 'x3': 270, 'y3': 400, 'x4': 586, 'y4': 404}, 'is_key': 0, 'row_id': '1', 'text': 'Margherita'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 68, 'y1': 329, 'x2': 16, 'y2': 326, 'x3': 14, 'y3': 399, 'x4': 63, 'y4': 391}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1124, 'y1': 330, 'x2': 946, 'y2': 337, 'x3': 955, 'y3': 397, 'x4': 1120, 'y4': 404}, 'is_key': 0, 'row_id': '1', 'text': '14,78'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 152, 'y1': 329, 'x2': 80, 'y2': 326, 'x3': 78, 'y3': 396, 'x4': 147, 'y4': 397}, 'is_key': 0, 'row_id': '1', 'text': '32'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 186, 'y1': 552, 'x2': 18, 'y2': 549, 'x3': 14, 'y3': 619, 'x4': 185, 'y4': 616}, 'is_key': 0, 'row_id': '2', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 206, 'y1': 672, 'x2': 15, 'y2': 671, 'x3': 14, 'y3': 612, 'x4': 210, 'y4': 615}, 'is_key': 0, 'row_id': '3', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1150, 'y1': 682, 'x2': 984, 'y2': 673, 'x3': 984, 'y3': 623, 'x4': 1155, 'y4': 624}, 'is_key': 0, 'row_id': '3', 'text': '14,78'}], 'category': 'total.cashprice', 'group_id': '3', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 887, 'x4': 0, 'y4': 887}}
13:
name =  Pan
name =  Crazy
name =  Dog
count =  1
15,49
price =  15,49
size =  32
Netto(sub_total_price) =  14,48
Gesamt(total_price) =  15,49
{'gt_parse': {'menu': [{'nm': 'Pan Crazy Dog', 'cnt': '1', 'price': '15,49', 'etc': '32'}], 'sub_total': {'subtotal_price': '14,48'}, 'total': {'total_price': '15,49'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 13, 'image_size': {'width': 1280, 'height': 925}}, 'valid_line': [{'words': [{'quad': {'x1': 168, 'y1': 283, 'x2': 256, 'y2': 289, 'x3': 258, 'y3': 348, 'x4': 171, 'y4': 352}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 282, 'y1': 283, 'x2': 417, 'y2': 290, 'x3': 413, 'y3': 361, 'x4': 277, 'y4': 349}, 'is_key': 0, 'row_id': '1', 'text': 'Crazy'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 433, 'y1': 286, 'x2': 533, 'y2': 296, 'x3': 534, 'y3': 361, 'x4': 437, 'y4': 358}, 'is_key': 0, 'row_id': '1', 'text': 'Dog'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 71, 'y1': 289, 'x2': 25, 'y2': 282, 'x3': 22, 'y3': 348, 'x4': 77, 'y4': 347}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1079, 'y1': 281, 'x2': 936, 'y2': 286, 'x3': 929, 'y3': 348, 'x4': 1090, 'y4': 356}, 'is_key': 0, 'row_id': '1', 'text': '15,49'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 147, 'y1': 283, 'x2': 85, 'y2': 289, 'x3': 87, 'y3': 351, 'x4': 147, 'y4': 351}, 'is_key': 0, 'row_id': '1', 'text': '32'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 189, 'y1': 610, 'x2': 11, 'y2': 607, 'x3': 11, 'y3': 676, 'x4': 186, 'y4': 678}, 'is_key': 0, 'row_id': '2', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 200, 'y1': 731, 'x2': 14, 'y2': 725, 'x3': 15, 'y3': 671, 'x4': 205, 'y4': 676}, 'is_key': 0, 'row_id': '2', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '2', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 925, 'x4': 0, 'y4': 925}}
14:
name =  Pizza-Br
name =  Salami
name =  Lava
name =  Cake
count =  1
2,99
price =  2,99
Netto(sub_total_price) =  8,39
Gesamt(total_price) =  8,98
total_credit =  8,98
total_credit(PayPal) =  8,98
total_credit =  8,98
{'gt_parse': {'menu': [{'nm': 'Pizza-Br Salami', 'cnt': '1', 'price': '5,99'}, {'nm': 'Lava Cake', 'cnt': '1', 'price': '2,99'}], 'sub_total': {'subtotal_price': '8,39'}, 'total': {'total_price': '8,98', 'creditcardprice': '8,98'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 14, 'image_size': {'width': 1280, 'height': 790}}, 'valid_line': [{'words': [{'quad': {'x1': 129, 'y1': 309, 'x2': 372, 'y2': 315, 'x3': 366, 'y3': 375, 'x4': 124, 'y4': 373}, 'is_key': 0, 'row_id': '1', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 386, 'y1': 310, 'x2': 570, 'y2': 310, 'x3': 566, 'y3': 377, 'x4': 384, 'y4': 377}, 'is_key': 0, 'row_id': '1', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 129, 'y1': 429, 'x2': 261, 'y2': 429, 'x3': 257, 'y3': 373, 'x4': 128, 'y4': 375}, 'is_key': 0, 'row_id': '2', 'text': 'Lava'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 405, 'y1': 430, 'x2': 405, 'y2': 373, 'x3': 272, 'y3': 376, 'x4': 275, 'y4': 438}, 'is_key': 0, 'row_id': '2', 'text': 'Cake'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 73, 'y1': 315, 'x2': 18, 'y2': 310, 'x3': 14, 'y3': 377, 'x4': 67, 'y4': 380}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1094, 'y1': 427, 'x2': 962, 'y2': 430, 'x3': 958, 'y3': 373, 'x4': 1094, 'y4': 373}, 'is_key': 0, 'row_id': '2', 'text': '2,99'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 186, 'y1': 472, 'x2': 16, 'y2': 477, 'x3': 14, 'y3': 542, 'x4': 194, 'y4': 534}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 210, 'y1': 587, 'x2': 22, 'y2': 594, 'x3': 22, 'y3': 538, 'x4': 210, 'y4': 533}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1126, 'y1': 586, 'x2': 996, 'y2': 589, 'x3': 994, 'y3': 538, 'x4': 1127, 'y4': 534}, 'is_key': 0, 'row_id': '4', 'text': '8,98'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 205, 'y1': 709, 'x2': 6, 'y2': 710, 'x3': 13, 'y3': 643, 'x4': 209, 'y4': 646}, 'is_key': 0, 'row_id': '5', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1122, 'y1': 624, 'x2': 970, 'y2': 633, 'x3': 982, 'y3': 705, 'x4': 1128, 'y4': 709}, 'is_key': 0, 'row_id': '5', 'text': '8,98'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 790, 'x4': 0, 'y4': 790}}
15:
name =  Penne
name =  Pasta
name =  Orlando
name =  Chicken
name =  Kickers
name =  Chicken
name =  Strippers
count =  1
5,99
price =  5,99
Netto(sub_total_price) =  20,54
Gesamt(total_price) =  21,97
total_credit =  21,97
total_credit(PayPal) =  21,97
total_credit =  21,97

23:
name =  Penne
name =  Pasta
name =  Orlando
count =  1
5,94
price =  5,94
Netto(sub_total_price) =  5,55
Gesamt(total_price) =  5,94
total_credit =  5,94
total_credit(EC) =  5,94
total_credit(Karte) =  5,94
total_credit =  5,94
{'gt_parse': {'menu': [{'nm': 'Penne Pasta Orlando', 'cnt': '1', 'price': '5,94'}], 'sub_total': {'subtotal_price': '5,55'}, 'total': {'total_price': '5,94', 'creditcardprice': '5,94'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 23, 'image_size': {'width': 864, 'height': 422}}, 'valid_line': [{'words': [{'quad': {'x1': 209, 'y1': 155, 'x2': 109, 'y2': 151, 'x3': 114, 'y3': 190, 'x4': 215, 'y4': 190}, 'is_key': 0, 'row_id': '1', 'text': 'Penne'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 311, 'y1': 153, 'x2': 223, 'y2': 154, 'x3': 220, 'y3': 190, 'x4': 314, 'y4': 193}, 'is_key': 0, 'row_id': '1', 'text': 'Pasta'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 451, 'y1': 152, 'x2': 320, 'y2': 153, 'x3': 323, 'y3': 199, 'x4': 455, 'y4': 197}, 'is_key': 0, 'row_id': '1', 'text': 'Orlando'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 79, 'y1': 154, 'x2': 48, 'y2': 153, 'x3': 48, 'y3': 189, 'x4': 81, 'y4': 185}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 615, 'y1': 156, 'x2': 701, 'y2': 155, 'x3': 700, 'y3': 197, 'x4': 620, 'y4': 196}, 'is_key': 0, 'row_id': '1', 'text': '5,94'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 45, 'y1': 244, 'x2': 147, 'y2': 247, 'x3': 147, 'y3': 284, 'x4': 44, 'y4': 281}, 'is_key': 0, 'row_id': '2', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 162, 'y1': 313, 'x2': 45, 'y2': 310, 'x3': 46, 'y3': 281, 'x4': 162, 'y4': 284}, 'is_key': 0, 'row_id': '3', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 720, 'y1': 316, 'x2': 637, 'y2': 315, 'x3': 635, 'y3': 284, 'x4': 720, 'y4': 282}, 'is_key': 0, 'row_id': '3', 'text': '5,94'}], 'category': 'total.creditcardprice', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 95, 'y1': 343, 'x2': 46, 'y2': 343, 'x3': 46, 'y3': 376, 'x4': 96, 'y4': 378}, 'is_key': 0, 'row_id': '4', 'text': 'EC'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 197, 'y1': 383, 'x2': 192, 'y2': 345, 'x3': 102, 'y3': 345, 'x4': 101, 'y4': 384}, 'is_key': 0, 'row_id': '4', 'text': 'Karte'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 718, 'y1': 340, 'x2': 643, 'y2': 343, 'x3': 640, 'y3': 378, 'x4': 723, 'y4': 382}, 'is_key': 0, 'row_id': '4', 'text': '5,94'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 864, 'y2': 0, 'x3': 864, 'y3': 422, 'x4': 0, 'y4': 422}}
24:
name =  Pan
name =  Tuna
name =  500ml
name =  Vio
name =  Bio
name =  Zitrone
count =  1
2,99
price =  2,99
Netto(sub_total_price) =  11,59
Gesamt(total_price) =  12,73
cashprice(Bar) =  12,73
{'gt_parse': {'menu': [{'nm': 'Pan Tuna', 'cnt': '1', 'price': '9,49'}, {'nm': '500ml Vio Bio Zitrone', 'cnt': '1', 'price': '2,99'}], 'sub_total': {'subtotal_price': '11,59'}, 'total': {'total_price': '12,73', 'cashprice': '12,73'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 24, 'image_size': {'width': 983, 'height': 634}}, 'valid_line': [{'words': [{'quad': {'x1': 204, 'y1': 214, 'x2': 141, 'y2': 214, 'x3': 138, 'y3': 259, 'x4': 214, 'y4': 258}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 324, 'y1': 212, 'x2': 226, 'y2': 209, 'x3': 225, 'y3': 260, 'x4': 323, 'y4': 260}, 'is_key': 0, 'row_id': '1', 'text': 'Tuna'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 189, 'y1': 290, 'x2': 82, 'y2': 292, 'x3': 81, 'y3': 337, 'x4': 191, 'y4': 335}, 'is_key': 0, 'row_id': '2', 'text': '500ml'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 271, 'y1': 289, 'x2': 200, 'y2': 290, 'x3': 202, 'y3': 335, 'x4': 275, 'y4': 331}, 'is_key': 0, 'row_id': '2', 'text': 'Vio'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 352, 'y1': 286, 'x2': 286, 'y2': 285, 'x3': 288, 'y3': 336, 'x4': 357, 'y4': 332}, 'is_key': 0, 'row_id': '2', 'text': 'Bio'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 521, 'y1': 297, 'x2': 369, 'y2': 289, 'x3': 369, 'y3': 340, 'x4': 529, 'y4': 335}, 'is_key': 0, 'row_id': '2', 'text': 'Zitrone'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 68, 'y1': 212, 'x2': 36, 'y2': 208, 'x3': 37, 'y3': 256, 'x4': 70, 'y4': 252}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 830, 'y1': 284, 'x2': 727, 'y2': 289, 'x3': 731, 'y3': 338, 'x4': 832, 'y4': 332}, 'is_key': 0, 'row_id': '2', 'text': '2,99'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 145, 'y1': 406, 'x2': 36, 'y2': 401, 'x3': 33, 'y3': 450, 'x4': 156, 'y4': 450}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 171, 'y1': 490, 'x2': 31, 'y2': 492, 'x3': 34, 'y3': 449, 'x4': 174, 'y4': 445}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 854, 'y1': 489, 'x2': 741, 'y2': 488, 'x3': 738, 'y3': 453, 'x4': 862, 'y4': 451}, 'is_key': 0, 'row_id': '4', 'text': '12,73'}], 'category': 'total.cashprice', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 983, 'y2': 0, 'x3': 983, 'y3': 634, 'x4': 0, 'y4': 634}}
25:
name =  Pan
name =  Bombay
name =  Pizza-Br
name =  Knoblauch
name =  Kأ¤se
count =  1
5,99
price =  5,99
Netto(sub_total_price) =  20,53
Gesamt(total_price) =  21,97
{'gt_parse': {'menu': [{'nm': 'Pan Bombay', 'cnt': '1', 'price': '15,98', 'etc': '1'}, {'nm': 'Pizza-Br Knoblauch Kأ¤se', 'cnt': '1', 'price': '5,99'}], 'sub_total': {'subtotal_price': '20,53'}, 'total': {'total_price': '21,97'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 25, 'image_size': {'width': 867, 'height': 544}}, 'valid_line': [{'words': [{'quad': {'x1': 197, 'y1': 191, 'x2': 136, 'y2': 190, 'x3': 137, 'y3': 231, 'x4': 195, 'y4': 232}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 317, 'y1': 193, 'x2': 209, 'y2': 191, 'x3': 206, 'y3': 232, 'x4': 312, 'y4': 238}, 'is_key': 0, 'row_id': '1', 'text': 'Bombay'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 269, 'y1': 294, 'x2': 119, 'y2': 289, 'x3': 115, 'y3': 330, 'x4': 265, 'y4': 337}, 'is_key': 0, 'row_id': '2', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 439, 'y1': 289, 'x2': 277, 'y2': 284, 'x3': 276, 'y3': 342, 'x4': 440, 'y4': 342}, 'is_key': 0, 'row_id': '2', 'text': 'Knoblauch'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 534, 'y1': 298, 'x2': 449, 'y2': 292, 'x3': 451, 'y3': 341, 'x4': 538, 'y4': 335}, 'is_key': 0, 'row_id': '2', 'text': 'Kأ¤se'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 79, 'y1': 190, 'x2': 50, 'y2': 188, 'x3': 45, 'y3': 225, 'x4': 78, 'y4': 223}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 719, 'y1': 290, 'x2': 630, 'y2': 290, 'x3': 628, 'y3': 333, 'x4': 715, 'y4': 338}, 'is_key': 0, 'row_id': '2', 'text': '5,99'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 148, 'y1': 353, 'x2': 43, 'y2': 349, 'x3': 43, 'y3': 394, 'x4': 152, 'y4': 392}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 166, 'y1': 428, 'x2': 48, 'y2': 428, 'x3': 45, 'y3': 395, 'x4': 167, 'y4': 394}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 867, 'y2': 0, 'x3': 867, 'y3': 544, 'x4': 0, 'y4': 544}}
26:
name =  Pan
name =  BBQ
name =  Poncho
count =  1
14,49
price =  14,49
size =  32
Netto(sub_total_price) =  13,54
Gesamt(total_price) =  14,49
cashprice(Bar) =  14,49
{'gt_parse': {'menu': [{'nm': 'Pan BBQ Poncho', 'cnt': '1', 'price': '14,49', 'etc': '32'}], 'sub_total': {'subtotal_price': '13,54'}, 'total': {'total_price': '14,49', 'cashprice': '14,49'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 26, 'image_size': {'width': 800, 'height': 450}}, 'valid_line': [{'words': [{'quad': {'x1': 161, 'y1': 179, 'x2': 109, 'y2': 177, 'x3': 108, 'y3': 214, 'x4': 169, 'y4': 212}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 237, 'y1': 176, 'x2': 172, 'y2': 177, 'x3': 173, 'y3': 213, 'x4': 237, 'y4': 211}, 'is_key': 0, 'row_id': '1', 'text': 'BBQ'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 351, 'y1': 179, 'x2': 245, 'y2': 179, 'x3': 243, 'y3': 214, 'x4': 351, 'y4': 211}, 'is_key': 0, 'row_id': '1', 'text': 'Poncho'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 47, 'y1': 180, 'x2': 18, 'y2': 179, 'x3': 17, 'y3': 211, 'x4': 47, 'y4': 209}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 664, 'y1': 171, 'x2': 568, 'y2': 173, 'x3': 573, 'y3': 211, 'x4': 665, 'y4': 212}, 'is_key': 0, 'row_id': '1', 'text': '14,49'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 98, 'y1': 176, 'x2': 57, 'y2': 176, 'x3': 56, 'y3': 210, 'x4': 98, 'y4': 210}, 'is_key': 0, 'row_id': '1', 'text': '32'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 21, 'y1': 267, 'x2': 122, 'y2': 265, 'x3': 120, 'y3': 305, 'x4': 20, 'y4': 308}, 'is_key': 0, 'row_id': '2', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 130, 'y1': 332, 'x2': 21, 'y2': 335, 'x3': 20, 'y3': 308, 'x4': 134, 'y4': 302}, 'is_key': 0, 'row_id': '3', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 689, 'y1': 326, 'x2': 600, 'y2': 334, 'x3': 593, 'y3': 301, 'x4': 690, 'y4': 296}, 'is_key': 0, 'row_id': '3', 'text': '14,49'}], 'category': 'total.cashprice', 'group_id': '3', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 800, 'y2': 0, 'x3': 800, 'y3': 450, 'x4': 0, 'y4': 450}}
27:
name =  Penne
name =  Pasta
name =  Chicko
name =  Pan
name =  Tuna
count =  1
15,99
price =  15,99
size =  32
Netto(sub_total_price) =  25,21
Gesamt(total_price) =  26,98
total_credit =  26,98
total_credit(PayPal) =  26,98
total_credit =  26,98
{'gt_parse': {'menu': [{'nm': 'Penne Pasta Chicko', 'cnt': '1', 'price': '10,99'}, {'nm': 'Pan Tuna', 'cnt': '1', 'price': '15,99', 'etc': '32'}], 'sub_total': {'subtotal_price': '25,21'}, 'total': {'total_price': '26,98', 'creditcardprice': '26,98'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 27, 'image_size': {'width': 1280, 'height': 912}}, 'valid_line': [{'words': [{'quad': {'x1': 122, 'y1': 331, 'x2': 281, 'y2': 343, 'x3': 282, 'y3': 400, 'x4': 122, 'y4': 395}, 'is_key': 0, 'row_id': '1', 'text': 'Penne'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 443, 'y1': 334, 'x2': 296, 'y2': 332, 'x3': 295, 'y3': 405, 'x4': 451, 'y4': 405}, 'is_key': 0, 'row_id': '1', 'text': 'Pasta'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 643, 'y1': 338, 'x2': 467, 'y2': 337, 'x3': 465, 'y3': 421, 'x4': 649, 'y4': 417}, 'is_key': 0, 'row_id': '1', 'text': 'Chicko'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 253, 'y1': 510, 'x2': 161, 'y2': 505, 'x3': 161, 'y3': 451, 'x4': 251, 'y4': 455}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 385, 'y1': 450, 'x2': 270, 'y2': 446, 'x3': 270, 'y3': 513, 'x4': 398, 'y4': 510}, 'is_key': 0, 'row_id': '2', 'text': 'Tuna'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 78, 'y1': 333, 'x2': 16, 'y2': 329, 'x3': 15, 'y3': 399, 'x4': 75, 'y4': 394}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1075, 'y1': 451, 'x2': 927, 'y2': 452, 'x3': 934, 'y3': 517, 'x4': 1084, 'y4': 516}, 'is_key': 0, 'row_id': '2', 'text': '15,99'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 148, 'y1': 451, 'x2': 75, 'y2': 448, 'x3': 77, 'y3': 509, 'x4': 149, 'y4': 504}, 'is_key': 0, 'row_id': '2', 'text': '32'}], 'category': 'menu.etc', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 175, 'y1': 604, 'x2': 8, 'y2': 599, 'x3': 5, 'y3': 665, 'x4': 182, 'y4': 665}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 199, 'y1': 721, 'x2': 11, 'y2': 719, 'x3': 10, 'y3': 662, 'x4': 200, 'y4': 662}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1110, 'y1': 727, 'x2': 950, 'y2': 728, 'x3': 952, 'y3': 670, 'x4': 1110, 'y4': 671}, 'is_key': 0, 'row_id': '4', 'text': '26,98'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 195, 'y1': 768, 'x2': 11, 'y2': 768, 'x3': 6, 'y3': 839, 'x4': 206, 'y4': 836}, 'is_key': 0, 'row_id': '5', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1104, 'y1': 761, 'x2': 938, 'y2': 765, 'x3': 941, 'y3': 852, 'x4': 1115, 'y4': 852}, 'is_key': 0, 'row_id': '5', 'text': '26,98'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 912, 'x4': 0, 'y4': 912}}
28:
name =  Pan
name =  Lunch
name =  Broccoli
name =  Hollan
name =  Pan
name =  Lunch
name =  Broccoli
name =  Hollan
name =  Chicken
name =  Strippers
name =  Krأ¤uterremoulade
name =  Dip
count =  1
1,29
price =  1,29
Netto(sub_total_price) =  21,83
Gesamt(total_price) =  23,35
{'gt_parse': {'menu': [{'nm': 'Pan Lunch Broccoli Hollan', 'cnt': '1', 'price': '6,99', 'etc': '25'}, {'nm': 'Pan Lunch Broccoli Hollan', 'cnt': '1', 'price': '9,08', 'etc': '25'}, {'nm': 'Chicken Strippers', 'cnt': '1', 'price': '5,99'}, {'nm': 'Krأ¤uterremoulade Dip', 'cnt': '1', 'price': '1,29'}], 'sub_total': {'subtotal_price': '21,83'}, 'total': {'total_price': '23,35'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 28, 'image_size': {'width': 1280, 'height': 1074}}, 'valid_line': [{'words': [{'quad': {'x1': 264, 'y1': 322, 'x2': 168, 'y2': 321, 'x3': 167, 'y3': 389, 'x4': 271, 'y4': 385}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 438, 'y1': 308, 'x2': 277, 'y2': 310, 'x3': 284, 'y3': 387, 'x4': 448, 'y4': 378}, 'is_key': 0, 'row_id': '1', 'text': 'Lunch'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 672, 'y1': 300, 'x2': 451, 'y2': 301, 'x3': 455, 'y3': 387, 'x4': 682, 'y4': 378}, 'is_key': 0, 'row_id': '1', 'text': 'Broccoli'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 886, 'y1': 295, 'x2': 695, 'y2': 302, 'x3': 698, 'y3': 382, 'x4': 893, 'y4': 372}, 'is_key': 0, 'row_id': '1', 'text': 'Hollan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 260, 'y1': 438, 'x2': 166, 'y2': 441, 'x3': 170, 'y3': 502, 'x4': 263, 'y4': 492}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 430, 'y1': 435, 'x2': 283, 'y2': 439, 'x3': 283, 'y3': 492, 'x4': 434, 'y4': 488}, 'is_key': 0, 'row_id': '2', 'text': 'Lunch'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 682, 'y1': 419, 'x2': 449, 'y2': 431, 'x3': 454, 'y3': 498, 'x4': 689, 'y4': 485}, 'is_key': 0, 'row_id': '2', 'text': 'Broccoli'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 873, 'y1': 415, 'x2': 701, 'y2': 421, 'x3': 702, 'y3': 491, 'x4': 885, 'y4': 485}, 'is_key': 0, 'row_id': '2', 'text': 'Hollan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 345, 'y1': 605, 'x2': 126, 'y2': 610, 'x3': 131, 'y3': 670, 'x4': 347, 'y4': 655}, 'is_key': 0, 'row_id': '3', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 639, 'y1': 590, 'x2': 364, 'y2': 600, 'x3': 362, 'y3': 665, 'x4': 651, 'y4': 650}, 'is_key': 0, 'row_id': '3', 'text': 'Strippers'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 133, 'y1': 739, 'x2': 608, 'y2': 712, 'x3': 602, 'y3': 646, 'x4': 126, 'y4': 672}, 'is_key': 0, 'row_id': '4', 'text': 'Krأ¤uterremoulade'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 722, 'y1': 703, 'x2': 719, 'y2': 632, 'x3': 608, 'y3': 649, 'x4': 616, 'y4': 719}, 'is_key': 0, 'row_id': '4', 'text': 'Dip'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 73, 'y1': 327, 'x2': 11, 'y2': 327, 'x3': 9, 'y3': 395, 'x4': 73, 'y4': 389}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1114, 'y1': 699, 'x2': 963, 'y2': 702, 'x3': 959, 'y3': 645, 'x4': 1103, 'y4': 638}, 'is_key': 0, 'row_id': '4', 'text': '1,29'}], 'category': 'menu.price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 176, 'y1': 783, 'x2': 10, 'y2': 790, 'x3': 10, 'y3': 856, 'x4': 193, 'y4': 839}, 'is_key': 0, 'row_id': '5', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 201, 'y1': 899, 'x2': 10, 'y2': 920, 'x3': 6, 'y3': 854, 'x4': 208, 'y4': 837}, 'is_key': 0, 'row_id': '6', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 1074, 'x4': 0, 'y4': 1074}}
29:
name =  Penne
name =  Pasta
name =  Orlando
name =  Pan
name =  Sucuk
name =  Hollandaise
name =  Cinnamon
name =  Bread
count =  1
2,15
price =  2,15
Netto(sub_total_price) =  18,22
Gesamt(total_price) =  19,49

38:
name =  GAR+CHE
name =  Prosciutto
name =  Suprem
name =  CHEESY
name =  Salami
name =  Supreme
name =  CHEESY
name =  Waikiki
count =  1
13,28
price =  13,28
size =  28
Netto(sub_total_price) =  38,44
Gesamt(total_price) =  41,13
total_credit =  41,13
total_credit(ApplePay) =  41,13
total_credit =  41,13
{'gt_parse': {'menu': [{'nm': 'GAR+CHE Prosciutto Suprem', 'cnt': '1', 'price': '14,57', 'etc': '28'}, {'nm': 'CHEESY Salami Supreme', 'cnt': '1', 'price': '13,28', 'etc': '28'}, {'nm': 'CHEESY Waikiki', 'cnt': '1', 'price': '13,28', 'etc': '28'}], 'sub_total': {'subtotal_price': '38,44'}, 'total': {'total_price': '41,13', 'creditcardprice': '41,13'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 38, 'image_size': {'width': 1280, 'height': 1039}}, 'valid_line': [{'words': [{'quad': {'x1': 391, 'y1': 280, 'x2': 382, 'y2': 360, 'x3': 198, 'y3': 366, 'x4': 190, 'y4': 274}, 'is_key': 0, 'row_id': '1', 'text': 'GAR+CHE'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 670, 'y1': 291, 'x2': 670, 'y2': 357, 'x3': 417, 'y3': 366, 'x4': 400, 'y4': 274}, 'is_key': 0, 'row_id': '1', 'text': 'Prosciutto'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 866, 'y1': 277, 'x2': 860, 'y2': 354, 'x3': 693, 'y3': 360, 'x4': 676, 'y4': 254}, 'is_key': 0, 'row_id': '1', 'text': 'Suprem'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 364, 'y1': 402, 'x2': 368, 'y2': 473, 'x3': 197, 'y3': 476, 'x4': 190, 'y4': 395}, 'is_key': 0, 'row_id': '2', 'text': 'CHEESY'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 540, 'y1': 395, 'x2': 542, 'y2': 457, 'x3': 390, 'y3': 461, 'x4': 380, 'y4': 390}, 'is_key': 0, 'row_id': '2', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 761, 'y1': 390, 'x2': 765, 'y2': 459, 'x3': 566, 'y3': 461, 'x4': 556, 'y4': 395}, 'is_key': 0, 'row_id': '2', 'text': 'Supreme'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 357, 'y1': 559, 'x2': 195, 'y2': 554, 'x3': 202, 'y3': 504, 'x4': 361, 'y4': 497}, 'is_key': 0, 'row_id': '3', 'text': 'CHEESY'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 575, 'y1': 495, 'x2': 580, 'y2': 573, 'x3': 378, 'y3': 575, 'x4': 366, 'y4': 492}, 'is_key': 0, 'row_id': '3', 'text': 'Waikiki'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 43, 'y1': 285, 'x2': 98, 'y2': 282, 'x3': 101, 'y3': 349, 'x4': 52, 'y4': 349}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 906, 'y1': 378, 'x2': 903, 'y2': 457, 'x3': 1074, 'y3': 454, 'x4': 1086, 'y4': 376}, 'is_key': 0, 'row_id': '2', 'text': '13,28'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 175, 'y1': 285, 'x2': 181, 'y2': 351, 'x3': 115, 'y3': 360, 'x4': 109, 'y4': 271}, 'is_key': 0, 'row_id': '1', 'text': '28'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 62, 'y1': 752, 'x2': 214, 'y2': 749, 'x3': 223, 'y3': 804, 'x4': 59, 'y4': 806}, 'is_key': 0, 'row_id': '4', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 252, 'y1': 802, 'x2': 240, 'y2': 870, 'x3': 48, 'y3': 878, 'x4': 31, 'y4': 818}, 'is_key': 0, 'row_id': '5', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 946, 'y1': 870, 'x2': 1105, 'y2': 875, 'x3': 1129, 'y3': 804, 'x4': 906, 'y4': 799}, 'is_key': 0, 'row_id': '5', 'text': '41,13'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 314, 'y1': 911, 'x2': 316, 'y2': 987, 'x3': 62, 'y3': 984, 'x4': 43, 'y4': 918}, 'is_key': 0, 'row_id': '6', 'text': 'ApplePay'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 926, 'y1': 892, 'x2': 1109, 'y2': 894, 'x3': 1109, 'y3': 982, 'x4': 940, 'y4': 980}, 'is_key': 0, 'row_id': '6', 'text': '41,13'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 1039, 'x4': 0, 'y4': 1039}}
39:
name =  Pan
name =  Crazy
name =  Dog
count =  1
6,29
price =  6,29
size =  25
Netto(sub_total_price) =  5,88
Gesamt(total_price) =  6,29
cashprice(Bar) =  6,29
{'gt_parse': {'menu': [{'nm': 'Pan Crazy Dog', 'cnt': '1', 'price': '6,29', 'etc': '25'}], 'sub_total': {'subtotal_price': '5,88'}, 'total': {'total_price': '6,29', 'cashprice': '6,29'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 39, 'image_size': {'width': 1280, 'height': 748}}, 'valid_line': [{'words': [{'quad': {'x1': 277, 'y1': 293, 'x2': 285, 'y2': 364, 'x3': 196, 'y3': 369, 'x4': 183, 'y4': 291}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 437, 'y1': 291, 'x2': 437, 'y2': 364, 'x3': 308, 'y3': 358, 'x4': 290, 'y4': 283}, 'is_key': 0, 'row_id': '1', 'text': 'Crazy'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 575, 'y1': 293, 'x2': 552, 'y2': 377, 'x3': 463, 'y3': 374, 'x4': 452, 'y4': 280}, 'is_key': 0, 'row_id': '1', 'text': 'Dog'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 52, 'y1': 293, 'x2': 97, 'y2': 298, 'x3': 99, 'y3': 361, 'x4': 52, 'y4': 364}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 943, 'y1': 259, 'x2': 1084, 'y2': 251, 'x3': 1094, 'y3': 348, 'x4': 958, 'y4': 348}, 'is_key': 0, 'row_id': '1', 'text': '6,29'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 178, 'y1': 288, 'x2': 178, 'y2': 364, 'x3': 105, 'y3': 369, 'x4': 110, 'y4': 288}, 'is_key': 0, 'row_id': '1', 'text': '25'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 52, 'y1': 461, 'x2': 199, 'y2': 461, 'x3': 193, 'y3': 524, 'x4': 37, 'y4': 526}, 'is_key': 0, 'row_id': '2', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 233, 'y1': 521, 'x2': 230, 'y2': 594, 'x3': 39, 'y3': 584, 'x4': 40, 'y4': 530}, 'is_key': 0, 'row_id': '3', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1008, 'y1': 558, 'x2': 1128, 'y2': 565, 'x3': 1144, 'y3': 498, 'x4': 979, 'y4': 498}, 'is_key': 0, 'row_id': '3', 'text': '6,29'}], 'category': 'total.cashprice', 'group_id': '3', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 748, 'x4': 0, 'y4': 748}}
3:
name =  Pan
name =  Meatlover
name =  Pan
name =  Dutchman
count =  1
10,49
price =  10,49
size =  28
Netto(sub_total_price) =  23,81
Gesamt(total_price) =  25,48
{'gt_parse': {'menu': [{'nm': 'Pan Meatlover', 'cnt': '1', 'price': '14,99', 'etc': '32'}, {'nm': 'Pan Dutchman', 'cnt': '1', 'price': '10,49', 'etc': '28'}], 'sub_total': {'subtotal_price': '23,81'}, 'total': {'total_price': '25,48'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 3, 'image_size': {'width': 1280, 'height': 882}}, 'valid_line': [{'words': [{'quad': {'x1': 182, 'y1': 302, 'x2': 269, 'y2': 311, 'x3': 275, 'y3': 374, 'x4': 177, 'y4': 368}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 284, 'y1': 307, 'x2': 550, 'y2': 309, 'x3': 544, 'y3': 390, 'x4': 286, 'y4': 373}, 'is_key': 0, 'row_id': '1', 'text': 'Meatlover'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 279, 'y1': 429, 'x2': 179, 'y2': 421, 'x3': 176, 'y3': 477, 'x4': 278, 'y4': 478}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 518, 'y1': 416, 'x2': 527, 'y2': 483, 'x3': 290, 'y3': 482, 'x4': 287, 'y4': 424}, 'is_key': 0, 'row_id': '2', 'text': 'Dutchman'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 32, 'y1': 314, 'x2': 81, 'y2': 312, 'x3': 86, 'y3': 378, 'x4': 36, 'y4': 375}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 923, 'y1': 412, 'x2': 1100, 'y2': 412, 'x3': 1103, 'y3': 494, 'x4': 920, 'y4': 489}, 'is_key': 0, 'row_id': '2', 'text': '10,49'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 164, 'y1': 429, 'x2': 92, 'y2': 423, 'x3': 95, 'y3': 478, 'x4': 161, 'y4': 478}, 'is_key': 0, 'row_id': '2', 'text': '28'}], 'category': 'menu.etc', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 32, 'y1': 573, 'x2': 209, 'y2': 578, 'x3': 198, 'y3': 636, 'x4': 27, 'y4': 637}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 29, 'y1': 699, 'x2': 242, 'y2': 693, 'x3': 243, 'y3': 640, 'x4': 27, 'y4': 642}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 882, 'x4': 0, 'y4': 882}}
40:
name =  Pan
name =  Grأ¼ner
name =  Garten
name =  Pizza-Br
name =  Spinat
name =  Kأ¤se
name =  Fuze
name =  Eistee
name =  Mango
count =  1
2,29
price =  2,29
size =  400ml
Netto(sub_total_price) =  16,59
Gesamt(total_price) =  18,02
total_credit =  18,02
total_credit(EC) =  18,02
total_credit(Karte) =  18,02
total_credit =  18,02
{'gt_parse': {'menu': [{'nm': 'Pan Grأ¼ner Garten', 'cnt': '1', 'price': '10,49', 'etc': '28'}, {'nm': 'Pizza-Br Spinat Kأ¤se', 'cnt': '1', 'price': '4,99'}, {'nm': 'Fuze Eistee Mango', 'cnt': '1', 'price': '2,29', 'etc': '400ml'}], 'sub_total': {'subtotal_price': '16,59'}, 'total': {'total_price': '18,02', 'creditcardprice': '18,02'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 40, 'image_size': {'width': 1280, 'height': 901}}, 'valid_line': [{'words': [{'quad': {'x1': 285, 'y1': 301, 'x2': 285, 'y2': 375, 'x3': 285, 'y3': 390, 'x4': 199, 'y4': 393}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 465, 'y1': 296, 'x2': 460, 'y2': 377, 'x3': 303, 'y3': 383, 'x4': 303, 'y4': 288}, 'is_key': 0, 'row_id': '1', 'text': 'Grأ¼ner'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 677, 'y1': 309, 'x2': 680, 'y2': 375, 'x3': 478, 'y3': 380, 'x4': 473, 'y4': 294}, 'is_key': 0, 'row_id': '1', 'text': 'Garten'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 173, 'y1': 469, 'x2': 276, 'y2': 474, 'x3': 397, 'y3': 479, 'x4': 397, 'y4': 417}, 'is_key': 0, 'row_id': '2', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 575, 'y1': 411, 'x2': 570, 'y2': 477, 'x3': 408, 'y3': 479, 'x4': 416, 'y4': 409}, 'is_key': 0, 'row_id': '2', 'text': 'Spinat'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 722, 'y1': 417, 'x2': 727, 'y2': 471, 'x3': 586, 'y3': 466, 'x4': 588, 'y4': 414}, 'is_key': 0, 'row_id': '2', 'text': 'Kأ¤se'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 401, 'y1': 519, 'x2': 277, 'y2': 517, 'x3': 277, 'y3': 474, 'x4': 404, 'y4': 474}, 'is_key': 0, 'row_id': '3', 'text': 'Fuze'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 580, 'y1': 533, 'x2': 410, 'y2': 538, 'x3': 414, 'y3': 465, 'x4': 577, 'y4': 462}, 'is_key': 0, 'row_id': '3', 'text': 'Eistee'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 747, 'y1': 464, 'x2': 748, 'y2': 543, 'x3': 590, 'y3': 545, 'x4': 596, 'y4': 475}, 'is_key': 0, 'row_id': '3', 'text': 'Mango'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 47, 'y1': 301, 'x2': 102, 'y2': 307, 'x3': 112, 'y3': 377, 'x4': 55, 'y4': 380}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 957, 'y1': 529, 'x2': 1095, 'y2': 532, 'x3': 1096, 'y3': 470, 'x4': 952, 'y4': 469}, 'is_key': 0, 'row_id': '3', 'text': '2,29'}], 'category': 'menu.price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 254, 'y1': 527, 'x2': 116, 'y2': 530, 'x3': 121, 'y3': 460, 'x4': 258, 'y4': 473}, 'is_key': 0, 'row_id': '3', 'text': '400ml'}], 'category': 'menu.etc', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 226, 'y1': 611, 'x2': 226, 'y2': 673, 'x3': 48, 'y3': 680, 'x4': 43, 'y4': 606}, 'is_key': 0, 'row_id': '4', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 238, 'y1': 725, 'x2': 59, 'y2': 739, 'x3': 45, 'y3': 680, 'x4': 238, 'y4': 663}, 'is_key': 0, 'row_id': '5', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 978, 'y1': 737, 'x2': 1128, 'y2': 751, 'x3': 1121, 'y3': 678, 'x4': 959, 'y4': 668}, 'is_key': 0, 'row_id': '5', 'text': '18,02'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 48, 'y1': 851, 'x2': 128, 'y2': 853, 'x3': 135, 'y3': 777, 'x4': 50, 'y4': 777}, 'is_key': 0, 'row_id': '6', 'text': 'EC'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 302, 'y1': 782, 'x2': 304, 'y2': 856, 'x3': 147, 'y3': 858, 'x4': 147, 'y4': 775}, 'is_key': 0, 'row_id': '6', 'text': 'Karte'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 955, 'y1': 754, 'x2': 1122, 'y2': 777, 'x3': 1112, 'y3': 844, 'x4': 974, 'y4': 846}, 'is_key': 0, 'row_id': '6', 'text': '18,02'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 901, 'x4': 0, 'y4': 901}}
41:
name =  Penne
name =  Pasta
name =  Bolo
name =  Pizza-Br
name =  Thunfisch
name =  Kأ¤se
name =  Knoblauch
name =  Dip
count =  1
1,29
price =  1,29
Netto(sub_total_price) =  16,61
Gesamt(total_price) =  17,77
total_credit =  17,77
{'gt_parse': {'menu': [{'nm': 'Penne Pasta Bolo', 'cnt': '1', 'price': '10,49'}, {'nm': 'Pizza-Br Thunfisch Kأ¤se', 'cnt': '1', 'price': '5,99'}, {'nm': 'Knoblauch Dip', 'cnt': '1', 'price': '1,29'}], 'sub_total': {'subtotal_price': '16,61'}, 'total': {'total_price': '17,77', 'creditcardprice': '17,77'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 41, 'image_size': {'width': 1280, 'height': 879}}, 'valid_line': [{'words': [{'quad': {'x1': 156, 'y1': 279, 'x2': 307, 'y2': 277, 'x3': 311, 'y3': 380, 'x4': 169, 'y4': 365}, 'is_key': 0, 'row_id': '1', 'text': 'Penne'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 452, 'y1': 285, 'x2': 458, 'y2': 369, 'x3': 324, 'y3': 374, 'x4': 318, 'y4': 264}, 'is_key': 0, 'row_id': '1', 'text': 'Pasta'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 599, 'y1': 294, 'x2': 607, 'y2': 367, 'x3': 475, 'y3': 376, 'x4': 471, 'y4': 277}, 'is_key': 0, 'row_id': '1', 'text': 'Bolo'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 151, 'y1': 441, 'x2': 382, 'y2': 449, 'x3': 387, 'y3': 510, 'x4': 166, 'y4': 510}, 'is_key': 0, 'row_id': '2', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 640, 'y1': 438, 'x2': 635, 'y2': 523, 'x3': 550, 'y3': 516, 'x4': 408, 'y4': 505}, 'is_key': 0, 'row_id': '2', 'text': 'Thunfisch'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 776, 'y1': 443, 'x2': 780, 'y2': 525, 'x3': 648, 'y3': 527, 'x4': 648, 'y4': 432}, 'is_key': 0, 'row_id': '2', 'text': 'Kأ¤se'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 175, 'y1': 568, 'x2': 406, 'y2': 573, 'x3': 402, 'y3': 501, 'x4': 169, 'y4': 503}, 'is_key': 0, 'row_id': '3', 'text': 'Knoblauch'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 529, 'y1': 560, 'x2': 419, 'y2': 567, 'x3': 423, 'y3': 505, 'x4': 530, 'y4': 514}, 'is_key': 0, 'row_id': '3', 'text': 'Dip'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 60, 'y1': 292, 'x2': 112, 'y2': 298, 'x3': 117, 'y3': 356, 'x4': 58, 'y4': 356}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 948, 'y1': 551, 'x2': 1086, 'y2': 562, 'x3': 1075, 'y3': 509, 'x4': 909, 'y4': 491}, 'is_key': 0, 'row_id': '3', 'text': '1,29'}], 'category': 'menu.price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 71, 'y1': 585, 'x2': 233, 'y2': 588, 'x3': 218, 'y3': 657, 'x4': 67, 'y4': 659}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 259, 'y1': 648, 'x2': 251, 'y2': 724, 'x3': 58, 'y3': 728, 'x4': 48, 'y4': 648}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1070, 'y1': 698, 'x2': 931, 'y2': 702, 'x3': 916, 'y3': 635, 'x4': 1080, 'y4': 642}, 'is_key': 0, 'row_id': '4', 'text': '17,77'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 879, 'x4': 0, 'y4': 879}}
42:
name =  New
name =  York
name =  Cheesecake
name =  Lava
name =  Sprite
count =  1
3,29
price =  3,29
size =  1
Netto(sub_total_price) =  9,02
Gesamt(total_price) =  10,02

55:
name =  Pan
name =  Waikiki
name =  BBQ
name =  Honey
name =  Dip
name =  Sour
name =  Creme
name =  Rأ¶sti
name =  Wrap
name =  Heiأںer
name =  Schlitten
count =  1
5,99
price =  5,99
Netto(sub_total_price) =  13,61
Gesamt(total_price) =  14,55
total_credit =  14,55
total_credit(PayPal) =  14,55
total_credit =  14,55
{'gt_parse': {'menu': [{'nm': 'Pan Waikiki', 'cnt': '1', 'price': '0,00', 'etc': '28'}, {'nm': 'BBQ Honey Dip', 'cnt': '1', 'price': '1,29'}, {'nm': 'Sour Creme', 'cnt': '1', 'price': '1,29'}, {'nm': 'Rأ¶sti ', 'cnt': '2', 'price': '5,98'}, {'nm': 'Wrap Heiأںer Schlitten', 'cnt': '1', 'price': '5,99'}], 'sub_total': {'subtotal_price': '13,61'}, 'total': {'total_price': '14,55', 'creditcardprice': '14,55'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 55, 'image_size': {'width': 1280, 'height': 977}}, 'valid_line': [{'words': [{'quad': {'x1': 279, 'y1': 285, 'x2': 279, 'y2': 355, 'x3': 196, 'y3': 357, 'x4': 192, 'y4': 288}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 505, 'y1': 283, 'x2': 499, 'y2': 359, 'x3': 309, 'y3': 355, 'x4': 294, 'y4': 274}, 'is_key': 0, 'row_id': '1', 'text': 'Waikiki'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 159, 'y1': 438, 'x2': 252, 'y2': 436, 'x3': 250, 'y3': 503, 'x4': 170, 'y4': 510}, 'is_key': 0, 'row_id': '2', 'text': 'BBQ'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 411, 'y1': 436, 'x2': 409, 'y2': 510, 'x3': 274, 'y3': 503, 'x4': 268, 'y4': 431}, 'is_key': 0, 'row_id': '2', 'text': 'Honey'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 531, 'y1': 444, 'x2': 531, 'y2': 512, 'x3': 433, 'y3': 505, 'x4': 424, 'y4': 433}, 'is_key': 0, 'row_id': '2', 'text': 'Dip'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 272, 'y1': 547, 'x2': 165, 'y2': 547, 'x3': 165, 'y3': 501, 'x4': 283, 'y4': 501}, 'is_key': 0, 'row_id': '3', 'text': 'Sour'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 440, 'y1': 564, 'x2': 311, 'y2': 566, 'x3': 296, 'y3': 494, 'x4': 444, 'y4': 503}, 'is_key': 0, 'row_id': '3', 'text': 'Creme'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 159, 'y1': 600, 'x2': 313, 'y2': 600, 'x3': 309, 'y3': 541, 'x4': 159, 'y4': 548}, 'is_key': 0, 'row_id': '4', 'text': 'Rأ¶sti'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 163, 'y1': 670, 'x2': 276, 'y2': 672, 'x3': 289, 'y3': 611, 'x4': 159, 'y4': 600}, 'is_key': 0, 'row_id': '5', 'text': 'Wrap'}], 'category': 'menu.nm', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 468, 'y1': 596, 'x2': 466, 'y2': 666, 'x3': 307, 'y3': 672, 'x4': 296, 'y4': 596}, 'is_key': 0, 'row_id': '5', 'text': 'Heiأںer'}], 'category': 'menu.nm', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 738, 'y1': 596, 'x2': 748, 'y2': 670, 'x3': 487, 'y3': 674, 'x4': 481, 'y4': 585}, 'is_key': 0, 'row_id': '5', 'text': 'Schlitten'}], 'category': 'menu.nm', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 49, 'y1': 276, 'x2': 108, 'y2': 269, 'x3': 101, 'y3': 344, 'x4': 49, 'y4': 344}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 951, 'y1': 661, 'x2': 1084, 'y2': 666, 'x3': 1075, 'y3': 598, 'x4': 960, 'y4': 596}, 'is_key': 0, 'row_id': '5', 'text': '5,99'}], 'category': 'menu.price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 213, 'y1': 700, 'x2': 209, 'y2': 757, 'x3': 59, 'y3': 759, 'x4': 44, 'y4': 687}, 'is_key': 0, 'row_id': '6', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 242, 'y1': 750, 'x2': 233, 'y2': 822, 'x3': 57, 'y3': 822, 'x4': 61, 'y4': 748}, 'is_key': 0, 'row_id': '7', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '7', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1104, 'y1': 825, 'x2': 956, 'y2': 822, 'x3': 956, 'y3': 750, 'x4': 1108, 'y4': 759}, 'is_key': 0, 'row_id': '7', 'text': '14,55'}], 'category': 'total.creditcardprice', 'group_id': '7', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 244, 'y1': 859, 'x2': 237, 'y2': 938, 'x3': 52, 'y3': 936, 'x4': 52, 'y4': 853}, 'is_key': 0, 'row_id': '8', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '8', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1102, 'y1': 851, 'x2': 1104, 'y2': 916, 'x3': 965, 'y3': 918, 'x4': 949, 'y4': 844}, 'is_key': 0, 'row_id': '8', 'text': '14,55'}], 'category': 'total.creditcardprice', 'group_id': '8', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 977, 'x4': 0, 'y4': 977}}
56:
name =  Pan
name =  Salami
name =  Jalapeno
name =  Cheese
name =  Bites
count =  1
4,99
price =  4,99
Netto(sub_total_price) =  17,72
Gesamt(total_price) =  18,96
total_credit =  18,96
total_credit(PayPal) =  18,96
total_credit =  18,96
{'gt_parse': {'menu': [{'nm': 'Pan Salami', 'cnt': '1', 'price': '13,97', 'etc': '28'}, {'nm': 'Jalapeno Cheese Bites', 'cnt': '1', 'price': '4,99'}], 'sub_total': {'subtotal_price': '17,72'}, 'total': {'total_price': '18,96', 'creditcardprice': '18,96'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 56, 'image_size': {'width': 1280, 'height': 898}}, 'valid_line': [{'words': [{'quad': {'x1': 298, 'y1': 298, 'x2': 306, 'y2': 357, 'x3': 221, 'y3': 363, 'x4': 212, 'y4': 285}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 489, 'y1': 294, 'x2': 482, 'y2': 373, 'x3': 320, 'y3': 381, 'x4': 309, 'y4': 276}, 'is_key': 0, 'row_id': '1', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 401, 'y1': 496, 'x2': 401, 'y2': 565, 'x3': 180, 'y3': 569, 'x4': 184, 'y4': 496}, 'is_key': 0, 'row_id': '2', 'text': 'Jalapeno'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 584, 'y1': 498, 'x2': 586, 'y2': 563, 'x3': 422, 'y3': 563, 'x4': 417, 'y4': 488}, 'is_key': 0, 'row_id': '2', 'text': 'Cheese'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 735, 'y1': 492, 'x2': 736, 'y2': 554, 'x3': 604, 'y3': 565, 'x4': 596, 'y4': 485}, 'is_key': 0, 'row_id': '2', 'text': 'Bites'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 124, 'y1': 300, 'x2': 138, 'y2': 357, 'x3': 86, 'y3': 359, 'x4': 74, 'y4': 305}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 943, 'y1': 480, 'x2': 1073, 'y2': 476, 'x3': 1078, 'y3': 557, 'x4': 958, 'y4': 553}, 'is_key': 0, 'row_id': '2', 'text': '4,99'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 227, 'y1': 605, 'x2': 227, 'y2': 670, 'x3': 85, 'y3': 668, 'x4': 77, 'y4': 602}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 246, 'y1': 660, 'x2': 250, 'y2': 714, 'x3': 78, 'y3': 717, 'x4': 68, 'y4': 663}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1107, 'y1': 707, 'x2': 968, 'y2': 712, 'x3': 968, 'y3': 653, 'x4': 1104, 'y4': 651}, 'is_key': 0, 'row_id': '4', 'text': '18,96'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 257, 'y1': 755, 'x2': 253, 'y2': 824, 'x3': 84, 'y3': 830, 'x4': 74, 'y4': 756}, 'is_key': 0, 'row_id': '5', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 961, 'y1': 734, 'x2': 1103, 'y2': 732, 'x3': 1106, 'y3': 816, 'x4': 957, 'y4': 817}, 'is_key': 0, 'row_id': '5', 'text': '18,96'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 898, 'x4': 0, 'y4': 898}}
57:
name =  Pan
name =  Sucuk
name =  Hollandaise
name =  Pan
name =  Danish
name =  Burger
name =  Pan
name =  Chicken
name =  Spargel
name =  Pizza-Br
name =  Kأ¤se
name =  Pizza-Br
name =  Chilisalami
name =  Pizza-Br
name =  Kأ¤se
name =  New
name =  York
name =  Lava
name =  Cake
name =  Lava
name =  Cake
count =  1
2,15
price =  2,15
Netto(sub_total_price) =  41,13
Gesamt(total_price) =  44,00
{'gt_parse': {'menu': [{'nm': 'Pan Sucuk Hollandaise', 'cnt': '1', 'price': '8,90', 'etc': '25'}, {'nm': 'Pan Danish Burger', 'cnt': '1', 'price': '8,25', 'etc': '25'}, {'nm': 'Pan Chicken Spargel', 'cnt': '1', 'price': '7,15', 'etc': '25'}, {'nm': 'Pizza-Br Kأ¤se', 'cnt': '1', 'price': '4,30'}, {'nm': 'Pizza-Br Chilisalami', 'cnt': '1', 'price': '4,30'}, {'nm': 'Pizza-Br Thunfisxh Kأ¤se', 'cnt': '1', 'price': '4,30'}, {'nm': 'New York Cheescake', 'cnt': '1', 'price': '2,50'}, {'nm': 'Lava Cake', 'cnt': '1', 'price': '2,15'}, {'nm': 'Lava Cake', 'cnt': '1', 'price': '2,15'}], 'sub_total': {'subtotal_price': '41,13'}, 'total': {'total_price': '44,00'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 57, 'image_size': {'width': 947, 'height': 1280}}, 'valid_line': [{'words': [{'quad': {'x1': 218, 'y1': 222, 'x2': 218, 'y2': 263, 'x3': 154, 'y3': 273, 'x4': 140, 'y4': 215}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 337, 'y1': 227, 'x2': 339, 'y2': 270, 'x3': 230, 'y3': 267, 'x4': 234, 'y4': 222}, 'is_key': 0, 'row_id': '1', 'text': 'Sucuk'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 573, 'y1': 230, 'x2': 577, 'y2': 280, 'x3': 351, 'y3': 269, 'x4': 346, 'y4': 221}, 'is_key': 0, 'row_id': '1', 'text': 'Hollandaise'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 217, 'y1': 339, 'x2': 217, 'y2': 384, 'x3': 153, 'y3': 384, 'x4': 149, 'y4': 337}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 355, 'y1': 342, 'x2': 358, 'y2': 388, 'x3': 229, 'y3': 389, 'x4': 229, 'y4': 338}, 'is_key': 0, 'row_id': '2', 'text': 'Danish'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 488, 'y1': 343, 'x2': 484, 'y2': 398, 'x3': 366, 'y3': 397, 'x4': 364, 'y4': 339}, 'is_key': 0, 'row_id': '2', 'text': 'Burger'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 219, 'y1': 459, 'x2': 218, 'y2': 502, 'x3': 152, 'y3': 498, 'x4': 150, 'y4': 445}, 'is_key': 0, 'row_id': '3', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 377, 'y1': 455, 'x2': 379, 'y2': 501, 'x3': 231, 'y3': 501, 'x4': 228, 'y4': 449}, 'is_key': 0, 'row_id': '3', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 425, 'y1': 455, 'x2': 573, 'y2': 456, 'x3': 566, 'y3': 516, 'x4': 429, 'y4': 510}, 'is_key': 0, 'row_id': '3', 'text': 'Spargel'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 298, 'y1': 572, 'x2': 300, 'y2': 623, 'x3': 127, 'y3': 616, 'x4': 128, 'y4': 565}, 'is_key': 0, 'row_id': '4', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 398, 'y1': 573, 'x2': 397, 'y2': 623, 'x3': 309, 'y3': 622, 'x4': 309, 'y4': 568}, 'is_key': 0, 'row_id': '4', 'text': 'Kأ¤se'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 126, 'y1': 644, 'x2': 289, 'y2': 646, 'x3': 291, 'y3': 695, 'x4': 121, 'y4': 691}, 'is_key': 0, 'row_id': '5', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 529, 'y1': 649, 'x2': 524, 'y2': 695, 'x3': 307, 'y3': 690, 'x4': 301, 'y4': 635}, 'is_key': 0, 'row_id': '5', 'text': 'Chilisalami'}], 'category': 'menu.nm', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 290, 'y1': 722, 'x2': 290, 'y2': 772, 'x3': 127, 'y3': 763, 'x4': 119, 'y4': 718}, 'is_key': 0, 'row_id': '6', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 584, 'y1': 725, 'x2': 586, 'y2': 771, 'x3': 502, 'y3': 768, 'x4': 498, 'y4': 723}, 'is_key': 0, 'row_id': '6', 'text': 'Kأ¤se'}], 'category': 'menu.nm', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 200, 'y1': 803, 'x2': 198, 'y2': 844, 'x3': 130, 'y3': 839, 'x4': 125, 'y4': 798}, 'is_key': 0, 'row_id': '7', 'text': 'New'}], 'category': 'menu.nm', 'group_id': '7', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 291, 'y1': 798, 'x2': 294, 'y2': 853, 'x3': 215, 'y3': 846, 'x4': 206, 'y4': 796}, 'is_key': 0, 'row_id': '7', 'text': 'York'}], 'category': 'menu.nm', 'group_id': '7', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 208, 'y1': 875, 'x2': 212, 'y2': 918, 'x3': 126, 'y3': 916, 'x4': 121, 'y4': 867}, 'is_key': 0, 'row_id': '8', 'text': 'Lava'}], 'category': 'menu.nm', 'group_id': '8', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 312, 'y1': 876, 'x2': 317, 'y2': 919, 'x3': 220, 'y3': 919, 'x4': 222, 'y4': 873}, 'is_key': 0, 'row_id': '8', 'text': 'Cake'}], 'category': 'menu.nm', 'group_id': '8', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 207, 'y1': 945, 'x2': 216, 'y2': 994, 'x3': 128, 'y3': 991, 'x4': 124, 'y4': 945}, 'is_key': 0, 'row_id': '9', 'text': 'Lava'}], 'category': 'menu.nm', 'group_id': '9', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 313, 'y1': 948, 'x2': 313, 'y2': 1000, 'x3': 227, 'y3': 996, 'x4': 224, 'y4': 950}, 'is_key': 0, 'row_id': '9', 'text': 'Cake'}], 'category': 'menu.nm', 'group_id': '9', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 83, 'y1': 217, 'x2': 83, 'y2': 262, 'x3': 57, 'y3': 267, 'x4': 53, 'y4': 215}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 708, 'y1': 881, 'x2': 793, 'y2': 881, 'x3': 793, 'y3': 923, 'x4': 710, 'y4': 926}, 'is_key': 0, 'row_id': '8', 'text': '2,15'}], 'category': 'menu.price', 'group_id': '8', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 151, 'y1': 1070, 'x2': 152, 'y2': 1108, 'x3': 47, 'y3': 1107, 'x4': 42, 'y4': 1063}, 'is_key': 0, 'row_id': '10', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '10', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 171, 'y1': 1104, 'x2': 171, 'y2': 1152, 'x3': 52, 'y3': 1150, 'x4': 51, 'y4': 1106}, 'is_key': 0, 'row_id': '11', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '11', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 947, 'y2': 0, 'x3': 947, 'y3': 1280, 'x4': 0, 'y4': 1280}}
58:
name =  Pizza-Br
name =  Prosciutto
name =  Kأ¤se
count =  2
11,98
price =  11,98
Netto(sub_total_price) =  12,41
Gesamt(total_price) =  12,27
total_credit =  13,27
total_credit(PayPal) =  13,27
total_credit =  13,27
{'gt_parse': {'menu': [{'nm': 'Pizza-Br Prosciutto Kأ¤se', 'cnt': '2', 'price': '11,98'}], 'sub_total': {'subtotal_price': '12,41'}, 'total': {'total_price': '12,27', 'creditcardprice': '13,27'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 58, 'image_size': {'width': 1280, 'height': 739}}, 'valid_line': [{'words': [{'quad': {'x1': 410, 'y1': 309, 'x2': 416, 'y2': 373, 'x3': 170, 'y3': 380, 'x4': 168, 'y4': 311}, 'is_key': 0, 'row_id': '1', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 696, 'y1': 298, 'x2': 707, 'y2': 364, 'x3': 427, 'y3': 380, 'x4': 427, 'y4': 295}, 'is_key': 0, 'row_id': '1', 'text': 'Prosciutto'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 840, 'y1': 297, 'x2': 837, 'y2': 364, 'x3': 720, 'y3': 364, 'x4': 709, 'y4': 293}, 'is_key': 0, 'row_id': '1', 'text': 'Kأ¤se'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 109, 'y1': 315, 'x2': 122, 'y2': 386, 'x3': 57, 'y3': 382, 'x4': 44, 'y4': 311}, 'is_key': 0, 'row_id': '1', 'text': '2'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 961, 'y1': 300, 'x2': 1097, 'y2': 289, 'x3': 1112, 'y3': 349, 'x4': 964, 'y4': 366}, 'is_key': 0, 'row_id': '1', 'text': '11,98'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 213, 'y1': 479, 'x2': 215, 'y2': 550, 'x3': 57, 'y3': 544, 'x4': 47, 'y4': 482}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 242, 'y1': 535, 'x2': 244, 'y2': 597, 'x3': 51, 'y3': 606, 'x4': 49, 'y4': 548}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1136, 'y1': 564, 'x2': 997, 'y2': 571, 'x3': 997, 'y3': 508, 'x4': 1141, 'y4': 500}, 'is_key': 0, 'row_id': '4', 'text': '13,27'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 248, 'y1': 648, 'x2': 244, 'y2': 732, 'x3': 58, 'y3': 730, 'x4': 42, 'y4': 644}, 'is_key': 0, 'row_id': '5', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1140, 'y1': 593, 'x2': 1154, 'y2': 675, 'x3': 996, 'y3': 688, 'x4': 987, 'y4': 608}, 'is_key': 0, 'row_id': '5', 'text': '13,27'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 739, 'x4': 0, 'y4': 739}}
59:
name =  Pan
name =  Margherita
name =  Pan
name =  Bombay
name =  Pan
name =  Waikiki
count =  1
0,00
price =  0,00
size =  28
Netto(sub_total_price) =  22,17
Gesamt(total_price) =  23,73
total_credit =  23,73
total_credit(PayPal) =  23,73
total_credit =  23,73

69:
name =  Pizza-Br
name =  Knoblauch
name =  Chicken
name =  Strippers
name =  Aioli
name =  Dip
name =  Wrap
name =  Classic
name =  Chicken
count =  1
4,99
price =  4,99
Netto(sub_total_price) =  15,19
Gesamt(total_price) =  16,26
cashprice(Bar) =  16,26
{'gt_parse': {'menu': [{'nm': 'Pizza-Br Knoblauch Kأ¤se', 'cnt': '1', 'price': '4,99'}, {'nm': 'Chicken Strippers', 'cnt': '1', 'price': '4,99'}, {'nm': 'Aioli Dip', 'cnt': '1', 'price': '1,29'}, {'nm': 'Wrap Classic Chicken', 'cnt': '1', 'price': '4,99'}], 'sub_total': {'subtotal_price': '15,19'}, 'total': {'total_price': '16,26', 'cashprice': '16,26'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 69, 'image_size': {'width': 1280, 'height': 868}}, 'valid_line': [{'words': [{'quad': {'x1': 180, 'y1': 340, 'x2': 337, 'y2': 338, 'x3': 414, 'y3': 337, 'x4': 414, 'y4': 397}, 'is_key': 0, 'row_id': '1', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 430, 'y1': 329, 'x2': 544, 'y2': 328, 'x3': 692, 'y3': 327, 'x4': 692, 'y4': 395}, 'is_key': 0, 'row_id': '1', 'text': 'Knoblauch'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 180, 'y1': 452, 'x2': 335, 'y2': 452, 'x3': 373, 'y3': 452, 'x4': 392, 'y4': 452}, 'is_key': 0, 'row_id': '2', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 405, 'y1': 447, 'x2': 438, 'y2': 453, 'x3': 673, 'y3': 452, 'x4': 678, 'y4': 392}, 'is_key': 0, 'row_id': '2', 'text': 'Strippers'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 172, 'y1': 509, 'x2': 332, 'y2': 506, 'x3': 332, 'y3': 451, 'x4': 172, 'y4': 454}, 'is_key': 0, 'row_id': '3', 'text': 'Aioli'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 349, 'y1': 505, 'x2': 439, 'y2': 512, 'x3': 451, 'y3': 455, 'x4': 345, 'y4': 447}, 'is_key': 0, 'row_id': '3', 'text': 'Dip'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 180, 'y1': 573, 'x2': 297, 'y2': 573, 'x3': 303, 'y3': 509, 'x4': 178, 'y4': 508}, 'is_key': 0, 'row_id': '4', 'text': 'Wrap'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 319, 'y1': 560, 'x2': 524, 'y2': 563, 'x3': 529, 'y3': 506, 'x4': 318, 'y4': 507}, 'is_key': 0, 'row_id': '4', 'text': 'Classic'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 549, 'y1': 498, 'x2': 549, 'y2': 568, 'x3': 747, 'y3': 560, 'x4': 745, 'y4': 496}, 'is_key': 0, 'row_id': '4', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 74, 'y1': 346, 'x2': 117, 'y2': 346, 'x3': 114, 'y3': 397, 'x4': 71, 'y4': 397}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1013, 'y1': 324, 'x2': 1133, 'y2': 327, 'x3': 1127, 'y3': 392, 'x4': 1010, 'y4': 392}, 'is_key': 0, 'row_id': '1', 'text': '4,99'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 65, 'y1': 608, 'x2': 210, 'y2': 605, 'x3': 213, 'y3': 675, 'x4': 67, 'y4': 679}, 'is_key': 0, 'row_id': '5', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 57, 'y1': 730, 'x2': 251, 'y2': 727, 'x3': 251, 'y3': 680, 'x4': 54, 'y4': 679}, 'is_key': 0, 'row_id': '6', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 983, 'y1': 691, 'x2': 1105, 'y2': 685, 'x3': 1119, 'y3': 637, 'x4': 982, 'y4': 641}, 'is_key': 0, 'row_id': '6', 'text': '16,26'}], 'category': 'total.cashprice', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 868, 'x4': 0, 'y4': 868}}
6:
name =  Pan
name =  Bombay
name =  Golden
name =  Chicken
name =  BBQ
name =  Honey
name =  Dip
count =  1
1,29
price =  1,29
Netto(sub_total_price) =  18,48
Gesamt(total_price) =  19,77
total_credit =  19,77
total_credit(PayPal) =  19,77
total_credit =  19,77
{'gt_parse': {'menu': [{'nm': 'Pan Bombay', 'cnt': '1', 'price': '12,49', 'etc': '28'}, {'nm': 'Golden Chicken', 'cnt': '1', 'price': '5,99'}, {'nm': 'BBQ Honey Dip', 'cnt': '1', 'price': '1,29'}], 'sub_total': {'subtotal_price': '18,48'}, 'total': {'total_price': '19,77', 'creditcardprice': '19,77'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 6, 'image_size': {'width': 1280, 'height': 855}}, 'valid_line': [{'words': [{'quad': {'x1': 258, 'y1': 290, 'x2': 170, 'y2': 296, 'x3': 168, 'y3': 366, 'x4': 272, 'y4': 362}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 485, 'y1': 296, 'x2': 279, 'y2': 296, 'x3': 279, 'y3': 368, 'x4': 480, 'y4': 372}, 'is_key': 0, 'row_id': '1', 'text': 'Bombay'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 123, 'y1': 411, 'x2': 326, 'y2': 406, 'x3': 332, 'y3': 474, 'x4': 131, 'y4': 470}, 'is_key': 0, 'row_id': '2', 'text': 'Golden'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 570, 'y1': 398, 'x2': 335, 'y2': 394, 'x3': 344, 'y3': 477, 'x4': 567, 'y4': 476}, 'is_key': 0, 'row_id': '2', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 135, 'y1': 537, 'x2': 243, 'y2': 542, 'x3': 243, 'y3': 468, 'x4': 132, 'y4': 472}, 'is_key': 0, 'row_id': '3', 'text': 'BBQ'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 413, 'y1': 537, 'x2': 257, 'y2': 535, 'x3': 252, 'y3': 468, 'x4': 423, 'y4': 477}, 'is_key': 0, 'row_id': '3', 'text': 'Honey'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 533, 'y1': 535, 'x2': 425, 'y2': 534, 'x3': 420, 'y3': 466, 'x4': 537, 'y4': 477}, 'is_key': 0, 'row_id': '3', 'text': 'Dip'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 12, 'y1': 298, 'x2': 77, 'y2': 291, 'x3': 75, 'y3': 353, 'x4': 18, 'y4': 353}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 966, 'y1': 520, 'x2': 1122, 'y2': 519, 'x3': 1116, 'y3': 465, 'x4': 969, 'y4': 462}, 'is_key': 0, 'row_id': '3', 'text': '1,29'}], 'category': 'menu.price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 14, 'y1': 636, 'x2': 203, 'y2': 630, 'x3': 198, 'y3': 568, 'x4': 18, 'y4': 567}, 'is_key': 0, 'row_id': '4', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 17, 'y1': 694, 'x2': 236, 'y2': 686, 'x3': 233, 'y3': 632, 'x4': 15, 'y4': 636}, 'is_key': 0, 'row_id': '5', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 995, 'y1': 698, 'x2': 1158, 'y2': 698, 'x3': 1158, 'y3': 624, 'x4': 989, 'y4': 630}, 'is_key': 0, 'row_id': '5', 'text': '19,77'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 29, 'y1': 816, 'x2': 230, 'y2': 813, 'x3': 222, 'y3': 742, 'x4': 12, 'y4': 750}, 'is_key': 0, 'row_id': '6', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 993, 'y1': 806, 'x2': 1154, 'y2': 808, 'x3': 1161, 'y3': 726, 'x4': 984, 'y4': 729}, 'is_key': 0, 'row_id': '6', 'text': '19,77'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 855, 'x4': 0, 'y4': 855}}
70:
name =  Pan
name =  Conchita
name =  Pan
name =  Salami
count =  1
0,00
price =  0,00
size =  32
Netto(sub_total_price) =  14,01
Gesamt(total_price) =  14,99
cashprice(Bar) =  14,99
{'gt_parse': {'menu': [{'nm': 'Pan Conchita', 'cnt': '1', 'price': '14,99', 'etc': '32'}, {'nm': 'Pan Salami', 'cnt': '1', 'price': '0,00', 'etc': '32'}], 'sub_total': {'subtotal_price': '14,01'}, 'total': {'total_price': '14,99', 'cashprice': '14,99'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 70, 'image_size': {'width': 1280, 'height': 941}}, 'valid_line': [{'words': [{'quad': {'x1': 185, 'y1': 302, 'x2': 281, 'y2': 305, 'x3': 283, 'y3': 373, 'x4': 185, 'y4': 375}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 305, 'y1': 305, 'x2': 542, 'y2': 307, 'x3': 542, 'y3': 378, 'x4': 305, 'y4': 375}, 'is_key': 0, 'row_id': '1', 'text': 'Conchita'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 185, 'y1': 419, 'x2': 283, 'y2': 427, 'x3': 289, 'y3': 490, 'x4': 185, 'y4': 490}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 300, 'y1': 419, 'x2': 482, 'y2': 416, 'x3': 485, 'y3': 490, 'x4': 305, 'y4': 492}, 'is_key': 0, 'row_id': '2', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 38, 'y1': 313, 'x2': 82, 'y2': 310, 'x3': 82, 'y3': 370, 'x4': 41, 'y4': 373}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 994, 'y1': 419, 'x2': 994, 'y2': 490, 'x3': 1114, 'y3': 487, 'x4': 1117, 'y4': 411}, 'is_key': 0, 'row_id': '2', 'text': '0,00'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 101, 'y1': 307, 'x2': 169, 'y2': 302, 'x3': 169, 'y3': 373, 'x4': 101, 'y4': 378}, 'is_key': 0, 'row_id': '1', 'text': '32'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 41, 'y1': 636, 'x2': 196, 'y2': 628, 'x3': 207, 'y3': 707, 'x4': 33, 'y4': 707}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 35, 'y1': 767, 'x2': 231, 'y2': 767, 'x3': 240, 'y3': 710, 'x4': 22, 'y4': 713}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 972, 'y1': 307, 'x2': 1114, 'y2': 313, 'x3': 1117, 'y3': 378, 'x4': 975, 'y4': 378}, 'is_key': 0, 'row_id': '1', 'text': '14,99'}], 'category': 'total.cashprice', 'group_id': '1', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 941, 'x4': 0, 'y4': 941}}
71:
name =  Pan
name =  Lucifer
name =  Pan
name =  Waikiki
count =  1
8,99
price =  8,99
size =  25
Netto(sub_total_price) =  16,80
Gesamt(total_price) =  17,98
cashprice(Bar) =  17,98
{'gt_parse': {'menu': [{'nm': 'Pan Lucifer', 'cnt': '1', 'price': '8,99', 'etc': '25'}, {'nm': 'Pan Waikiki', 'cnt': '1', 'price': '8,99', 'etc': '25'}], 'sub_total': {'subtotal_price': '16,80'}, 'total': {'total_price': '17,98', 'cashprice': '17,98'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 71, 'image_size': {'width': 1280, 'height': 871}}, 'valid_line': [{'words': [{'quad': {'x1': 264, 'y1': 316, 'x2': 264, 'y2': 381, 'x3': 169, 'y3': 389, 'x4': 166, 'y4': 316}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 493, 'y1': 313, 'x2': 493, 'y2': 384, 'x3': 281, 'y3': 384, 'x4': 281, 'y4': 313}, 'is_key': 0, 'row_id': '1', 'text': 'Lucifer'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 264, 'y1': 433, 'x2': 270, 'y2': 493, 'x3': 172, 'y3': 495, 'x4': 169, 'y4': 430}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 493, 'y1': 490, 'x2': 286, 'y2': 495, 'x3': 281, 'y3': 425, 'x4': 487, 'y4': 414}, 'is_key': 0, 'row_id': '2', 'text': 'Waikiki'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 14, 'y1': 318, 'x2': 65, 'y2': 316, 'x3': 65, 'y3': 384, 'x4': 25, 'y4': 387}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 983, 'y1': 359, 'x2': 1114, 'y2': 362, 'x3': 1114, 'y3': 289, 'x4': 980, 'y4': 291}, 'is_key': 0, 'row_id': '1', 'text': '8,99'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 144, 'y1': 313, 'x2': 150, 'y2': 381, 'x3': 82, 'y3': 387, 'x4': 79, 'y4': 313}, 'is_key': 0, 'row_id': '1', 'text': '25'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 30, 'y1': 604, 'x2': 191, 'y2': 599, 'x3': 191, 'y3': 664, 'x4': 30, 'y4': 670}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 35, 'y1': 721, 'x2': 218, 'y2': 721, 'x3': 221, 'y3': 664, 'x4': 16, 'y4': 667}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 991, 'y1': 697, 'x2': 1149, 'y2': 697, 'x3': 1168, 'y3': 631, 'x4': 989, 'y4': 629}, 'is_key': 0, 'row_id': '4', 'text': '17,98'}], 'category': 'total.cashprice', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 871, 'x4': 0, 'y4': 871}}
72:
name =  Pan
name =  Boston
name =  Pan
name =  Boston
name =  Pizza-Br
name =  Salami
name =  Knoblauch
name =  Dip
count =  1
1,29
price =  1,29
Netto(sub_total_price) =  19,59
Gesamt(total_price) =  20,96
cashprice(Bar) =  20,96
{'gt_parse': {'menu': [{'nm': 'Pan Boston', 'cnt': '1', 'price': '14,68', 'etc': '32'}, {'nm': 'Pan Boston', 'cnt': '1', 'price': '0,00', 'etc': '28'}, {'nm': 'Pizza-Br Salami', 'cnt': '1', 'price': '4,99'}, {'nm': 'Knoblauch Dip', 'cnt': '1', 'price': '1,29'}], 'sub_total': {'subtotal_price': '19,59'}, 'total': {'total_price': '20,96', 'cashprice': '20,96'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 72, 'image_size': {'width': 1280, 'height': 1094}}, 'valid_line': [{'words': [{'quad': {'x1': 182, 'y1': 288, 'x2': 289, 'y2': 288, 'x3': 281, 'y3': 373, 'x4': 182, 'y4': 370}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 308, 'y1': 291, 'x2': 498, 'y2': 297, 'x3': 501, 'y3': 365, 'x4': 308, 'y4': 378}, 'is_key': 0, 'row_id': '1', 'text': 'Boston'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 289, 'y1': 544, 'x2': 289, 'y2': 601, 'x3': 185, 'y3': 612, 'x4': 182, 'y4': 533}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 308, 'y1': 610, 'x2': 509, 'y2': 607, 'x3': 509, 'y3': 536, 'x4': 305, 'y4': 531}, 'is_key': 0, 'row_id': '2', 'text': 'Boston'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 163, 'y1': 778, 'x2': 414, 'y2': 773, 'x3': 417, 'y3': 710, 'x4': 150, 'y4': 718}, 'is_key': 0, 'row_id': '3', 'text': 'Pizza-Br'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 438, 'y1': 710, 'x2': 621, 'y2': 697, 'x3': 636, 'y3': 764, 'x4': 438, 'y4': 769}, 'is_key': 0, 'row_id': '3', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 167, 'y1': 839, 'x2': 452, 'y2': 837, 'x3': 452, 'y3': 772, 'x4': 160, 'y4': 779}, 'is_key': 0, 'row_id': '4', 'text': 'Knoblauch'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 581, 'y1': 835, 'x2': 592, 'y2': 767, 'x3': 466, 'y3': 767, 'x4': 473, 'y4': 830}, 'is_key': 0, 'row_id': '4', 'text': 'Dip'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 19, 'y1': 294, 'x2': 65, 'y2': 291, 'x3': 71, 'y3': 359, 'x4': 22, 'y4': 357}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1041, 'y1': 815, 'x2': 1170, 'y2': 817, 'x3': 1172, 'y3': 745, 'x4': 1037, 'y4': 752}, 'is_key': 0, 'row_id': '4', 'text': '1,29'}], 'category': 'menu.price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 65, 'y1': 914, 'x2': 233, 'y2': 928, 'x3': 229, 'y3': 879, 'x4': 60, 'y4': 868}, 'is_key': 0, 'row_id': '5', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 78, 'y1': 957, 'x2': 265, 'y2': 969, 'x3': 265, 'y3': 928, 'x4': 73, 'y4': 917}, 'is_key': 0, 'row_id': '6', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1031, 'y1': 972, 'x2': 1189, 'y2': 969, 'x3': 1201, 'y3': 910, 'x4': 1035, 'y4': 912}, 'is_key': 0, 'row_id': '6', 'text': '20,96'}], 'category': 'total.cashprice', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 1094, 'x4': 0, 'y4': 1094}}
73:
name =  Pan
name =  Teriyaki
name =  Chicken
name =  Pan
name =  Boston
name =  Pan
name =  Margherita
count =  1
0,00
price =  0,00
size =  28
Netto(sub_total_price) =  21,01
Gesamt(total_price) =  22,48
cashprice(Bar) =  22,48

83:
name =  Pan
name =  BBQ
name =  Poncho
name =  Lava
name =  Cake
name =  Krأ¤uterremoulade
name =  Dip
count =  1
1,29
price =  1,29
Netto(sub_total_price) =  12,88
Gesamt(total_price) =  13,78
total_credit =  13,78
total_credit(PayPal) =  13,78
total_credit =  13,78
{'gt_parse': {'menu': [{'nm': 'Pan BBQ Poncho', 'cnt': '1', 'price': '12,49', 'etc': '25'}, {'nm': 'Lava Cake', 'cnt': '1', 'price': '0,00'}, {'nm': 'Krأ¤uterremoulade Dip', 'cnt': '1', 'price': '1,29'}], 'sub_total': {'subtotal_price': '12,88'}, 'total': {'total_price': '13,78', 'creditcardprice': '13,78'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 83, 'image_size': {'width': 1280, 'height': 1022}}, 'valid_line': [{'words': [{'quad': {'x1': 166, 'y1': 305, 'x2': 261, 'y2': 311, 'x3': 259, 'y3': 368, 'x4': 163, 'y4': 365}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 281, 'y1': 311, 'x2': 379, 'y2': 311, 'x3': 379, 'y3': 371, 'x4': 278, 'y4': 373}, 'is_key': 0, 'row_id': '1', 'text': 'BBQ'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 395, 'y1': 311, 'x2': 580, 'y2': 316, 'x3': 588, 'y3': 373, 'x4': 392, 'y4': 379}, 'is_key': 0, 'row_id': '1', 'text': 'Poncho'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 139, 'y1': 545, 'x2': 259, 'y2': 540, 'x3': 261, 'y3': 480, 'x4': 133, 'y4': 480}, 'is_key': 0, 'row_id': '2', 'text': 'Lava'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 278, 'y1': 542, 'x2': 411, 'y2': 545, 'x3': 409, 'y3': 480, 'x4': 272, 'y4': 474}, 'is_key': 0, 'row_id': '2', 'text': 'Cake'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 599, 'y1': 663, 'x2': 128, 'y2': 662, 'x3': 128, 'y3': 589, 'x4': 599, 'y4': 586}, 'is_key': 0, 'row_id': '3', 'text': 'Krأ¤uterremoulade'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 615, 'y1': 586, 'x2': 714, 'y2': 594, 'x3': 720, 'y3': 665, 'x4': 618, 'y4': 668}, 'is_key': 0, 'row_id': '3', 'text': 'Dip'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 19, 'y1': 308, 'x2': 57, 'y2': 308, 'x3': 54, 'y3': 365, 'x4': 19, 'y4': 368}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1117, 'y1': 670, 'x2': 983, 'y2': 679, 'x3': 972, 'y3': 597, 'x4': 1127, 'y4': 602}, 'is_key': 0, 'row_id': '3', 'text': '1,29'}], 'category': 'menu.price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 177, 'y1': 758, 'x2': 16, 'y2': 752, 'x3': 16, 'y3': 687, 'x4': 182, 'y4': 700}, 'is_key': 0, 'row_id': '4', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 215, 'y1': 820, 'x2': 14, 'y2': 812, 'x3': 14, 'y3': 749, 'x4': 212, 'y4': 766}, 'is_key': 0, 'row_id': '5', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1147, 'y1': 834, 'x2': 989, 'y2': 837, 'x3': 997, 'y3': 769, 'x4': 1157, 'y4': 774}, 'is_key': 0, 'row_id': '5', 'text': '13,78'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 202, 'y1': 943, 'x2': 19, 'y2': 935, 'x3': 16, 'y3': 861, 'x4': 199, 'y4': 867}, 'is_key': 0, 'row_id': '6', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1141, 'y1': 959, 'x2': 983, 'y2': 943, 'x3': 980, 'y3': 867, 'x4': 1144, 'y4': 875}, 'is_key': 0, 'row_id': '6', 'text': '13,78'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 1022, 'x4': 0, 'y4': 1022}}
84:
name =  Pan
name =  Individuell
name =  Pan
name =  Bombay
count =  1
12,99
price =  12,99
size =  32
Netto(sub_total_price) =  20,63
Gesamt(total_price) =  22,07
cashprice(Bar) =  22,07
{'gt_parse': {'menu': [{'nm': 'Pan Individuell', 'cnt': '1', 'price': '9,08', 'etc': '25'}, {'nm': 'Pan Bombay', 'cnt': '1', 'price': '12,99', 'etc': '32'}], 'sub_total': {'subtotal_price': '20,63'}, 'total': {'total_price': '22,07', 'cashprice': '22,07'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 84, 'image_size': {'width': 1280, 'height': 1002}}, 'valid_line': [{'words': [{'quad': {'x1': 174, 'y1': 305, 'x2': 267, 'y2': 310, 'x3': 267, 'y3': 376, 'x4': 174, 'y4': 373}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 291, 'y1': 305, 'x2': 599, 'y2': 310, 'x3': 605, 'y3': 384, 'x4': 291, 'y4': 376}, 'is_key': 0, 'row_id': '1', 'text': 'Individuell'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 169, 'y1': 471, 'x2': 267, 'y2': 474, 'x3': 267, 'y3': 542, 'x4': 174, 'y4': 539}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 283, 'y1': 476, 'x2': 466, 'y2': 471, 'x3': 466, 'y3': 545, 'x4': 283, 'y4': 539}, 'is_key': 0, 'row_id': '2', 'text': 'Bombay'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 25, 'y1': 302, 'x2': 65, 'y2': 308, 'x3': 68, 'y3': 365, 'x4': 33, 'y4': 362}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1100, 'y1': 545, 'x2': 942, 'y2': 555, 'x3': 940, 'y3': 479, 'x4': 1095, 'y4': 479}, 'is_key': 0, 'row_id': '2', 'text': '12,99'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 161, 'y1': 536, 'x2': 93, 'y2': 536, 'x3': 84, 'y3': 474, 'x4': 153, 'y4': 476}, 'is_key': 0, 'row_id': '2', 'text': '32'}], 'category': 'menu.etc', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 180, 'y1': 746, 'x2': 22, 'y2': 746, 'x3': 22, 'y3': 683, 'x4': 185, 'y4': 683}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 204, 'y1': 809, 'x2': 27, 'y2': 803, 'x3': 27, 'y3': 746, 'x4': 204, 'y4': 749}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1119, 'y1': 817, 'x2': 961, 'y2': 817, 'x3': 964, 'y3': 757, 'x4': 1125, 'y4': 757}, 'is_key': 0, 'row_id': '4', 'text': '22,07'}], 'category': 'total.cashprice', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 1002, 'x4': 0, 'y4': 1002}}
85:
name =  Pan
name =  VEGAN
name =  Las
name =  Vega
name =  Pan
name =  Chicken
name =  Spargel
count =  1
11,49
price =  11,49
size =  28
Netto(sub_total_price) =  22,31
Gesamt(total_price) =  23,97
{'gt_parse': {'menu': [{'nm': 'Pan VEGAN Las Vega', 'cnt': '1', 'price': '11,49', 'etc': '25'}, {'nm': 'Pan Chicken Spargel', 'cnt': '1', 'price': '11,49', 'etc': '28'}], 'sub_total': {'subtotal_price': '22,31'}, 'total': {'total_price': '23,97'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 85, 'image_size': {'width': 1280, 'height': 938}}, 'valid_line': [{'words': [{'quad': {'x1': 246, 'y1': 314, 'x2': 246, 'y2': 379, 'x3': 153, 'y3': 374, 'x4': 156, 'y4': 314}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 262, 'y1': 314, 'x2': 415, 'y2': 316, 'x3': 412, 'y3': 374, 'x4': 267, 'y4': 371}, 'is_key': 0, 'row_id': '1', 'text': 'VEGAN'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 428, 'y1': 311, 'x2': 519, 'y2': 324, 'x3': 519, 'y3': 376, 'x4': 431, 'y4': 382}, 'is_key': 0, 'row_id': '1', 'text': 'Las'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 538, 'y1': 314, 'x2': 666, 'y2': 324, 'x3': 666, 'y3': 382, 'x4': 546, 'y4': 384}, 'is_key': 0, 'row_id': '1', 'text': 'Vega'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 150, 'y1': 420, 'x2': 246, 'y2': 425, 'x3': 248, 'y3': 483, 'x4': 153, 'y4': 491}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 265, 'y1': 420, 'x2': 467, 'y2': 431, 'x3': 464, 'y3': 491, 'x4': 265, 'y4': 483}, 'is_key': 0, 'row_id': '2', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 538, 'y1': 425, 'x2': 742, 'y2': 423, 'x3': 740, 'y3': 494, 'x4': 543, 'y4': 488}, 'is_key': 0, 'row_id': '2', 'text': 'Spargel'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 14, 'y1': 311, 'x2': 55, 'y2': 311, 'x3': 55, 'y3': 365, 'x4': 11, 'y4': 365}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 933, 'y1': 316, 'x2': 1086, 'y2': 316, 'x3': 1086, 'y3': 387, 'x4': 936, 'y4': 390}, 'is_key': 0, 'row_id': '1', 'text': '11,49'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 76, 'y1': 414, 'x2': 136, 'y2': 423, 'x3': 136, 'y3': 483, 'x4': 74, 'y4': 483}, 'is_key': 0, 'row_id': '2', 'text': '28'}], 'category': 'menu.etc', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 16, 'y1': 624, 'x2': 169, 'y2': 624, 'x3': 172, 'y3': 687, 'x4': 22, 'y4': 684}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 197, 'y1': 750, 'x2': 22, 'y2': 747, 'x3': 16, 'y3': 684, 'x4': 199, 'y4': 687}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 938, 'x4': 0, 'y4': 938}}
86:
name =  New
name =  York
name =  Cheesecake
name =  Lava
name =  Cake
name =  1L
name =  Sprite
count =  1
3,29
price =  3,29
Netto(sub_total_price) =  9,02
Gesamt(total_price) =  10,02
{'gt_parse': {'menu': [{'nm': 'New York Cheesecake', 'cnt': '1', 'price': '3,49'}, {'nm': 'Lava Cake', 'cnt': '1', 'price': '2,99'}, {'nm': '1L Sprite', 'cnt': '1', 'price': '3,29'}], 'sub_total': {'subtotal_price': '9,02'}, 'total': {'total_price': '10,02'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 86, 'image_size': {'width': 1280, 'height': 891}}, 'valid_line': [{'words': [{'quad': {'x1': 174, 'y1': 335, 'x2': 286, 'y2': 332, 'x3': 281, 'y3': 401, 'x4': 172, 'y4': 411}, 'is_key': 0, 'row_id': '1', 'text': 'New'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 302, 'y1': 332, 'x2': 433, 'y2': 322, 'x3': 436, 'y3': 395, 'x4': 305, 'y4': 401}, 'is_key': 0, 'row_id': '1', 'text': 'York'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 452, 'y1': 324, 'x2': 741, 'y2': 316, 'x3': 741, 'y3': 384, 'x4': 455, 'y4': 398}, 'is_key': 0, 'row_id': '1', 'text': 'Cheesecake'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 177, 'y1': 463, 'x2': 310, 'y2': 455, 'x3': 310, 'y3': 409, 'x4': 174, 'y4': 409}, 'is_key': 0, 'row_id': '2', 'text': 'Lava'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 460, 'y1': 447, 'x2': 330, 'y2': 455, 'x3': 324, 'y3': 398, 'x4': 468, 'y4': 398}, 'is_key': 0, 'row_id': '2', 'text': 'Cake'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 188, 'y1': 529, 'x2': 125, 'y2': 531, 'x3': 114, 'y3': 463, 'x4': 180, 'y4': 471}, 'is_key': 0, 'row_id': '3', 'text': '1L'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 204, 'y1': 520, 'x2': 406, 'y2': 510, 'x3': 406, 'y3': 452, 'x4': 196, 'y4': 460}, 'is_key': 0, 'row_id': '3', 'text': 'Sprite'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 41, 'y1': 351, 'x2': 84, 'y2': 351, 'x3': 84, 'y3': 406, 'x4': 41, 'y4': 406}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 1010, 'y1': 485, 'x2': 1136, 'y2': 493, 'x3': 1144, 'y3': 439, 'x4': 1010, 'y4': 431}, 'is_key': 0, 'row_id': '3', 'text': '3,29'}], 'category': 'menu.price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 52, 'y1': 638, 'x2': 215, 'y2': 624, 'x3': 221, 'y3': 684, 'x4': 54, 'y4': 695}, 'is_key': 0, 'row_id': '4', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 60, 'y1': 760, 'x2': 256, 'y2': 738, 'x3': 251, 'y3': 678, 'x4': 54, 'y4': 695}, 'is_key': 0, 'row_id': '5', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 891, 'x4': 0, 'y4': 891}}
87:
name =  Pan
name =  Lucifer
name =  1L
name =  Coca
name =  Cola
count =  1
3,29
price =  3,29
Netto(sub_total_price) =  13,10
Gesamt(total_price) =  14,38
{'gt_parse': {'menu': [{'nm': 'Pan Lucifer', 'cnt': '1', 'price': '10,84', 'etc': '32'}, {'nm': '1L Coca Cola', 'cnt': '1', 'price': '3,29'}], 'sub_total': {'subtotal_price': '13,10'}, 'total': {'total_price': '14,38'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 87, 'image_size': {'width': 1280, 'height': 947}}, 'valid_line': [{'words': [{'quad': {'x1': 188, 'y1': 321, 'x2': 286, 'y2': 318, 'x3': 286, 'y3': 381, 'x4': 193, 'y4': 381}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 305, 'y1': 316, 'x2': 501, 'y2': 318, 'x3': 504, 'y3': 386, 'x4': 308, 'y4': 386}, 'is_key': 0, 'row_id': '1', 'text': 'Lucifer'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 112, 'y1': 479, 'x2': 172, 'y2': 484, 'x3': 177, 'y3': 542, 'x4': 114, 'y4': 542}, 'is_key': 0, 'row_id': '2', 'text': '1L'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 188, 'y1': 484, 'x2': 308, 'y2': 490, 'x3': 313, 'y3': 542, 'x4': 193, 'y4': 539}, 'is_key': 0, 'row_id': '2', 'text': 'Coca'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 327, 'y1': 484, 'x2': 449, 'y2': 487, 'x3': 455, 'y3': 542, 'x4': 330, 'y4': 539}, 'is_key': 0, 'row_id': '2', 'text': 'Cola'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 54, 'y1': 318, 'x2': 87, 'y2': 321, 'x3': 90, 'y3': 376, 'x4': 57, 'y4': 376}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 975, 'y1': 539, 'x2': 1103, 'y2': 536, 'x3': 1111, 'y3': 479, 'x4': 983, 'y4': 482}, 'is_key': 0, 'row_id': '2', 'text': '3,29'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 54, 'y1': 637, 'x2': 196, 'y2': 637, 'x3': 202, 'y3': 702, 'x4': 49, 'y4': 702}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 46, 'y1': 767, 'x2': 223, 'y2': 770, 'x3': 221, 'y3': 702, 'x4': 52, 'y4': 697}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 947, 'x4': 0, 'y4': 947}}
88:
name =  Pan
name =  VEGAN
name =  Curry
name =  Pan
name =  Margherita
name =  Pan
name =  Margherita
count =  1
6,15
price =  6,15
size =  25
Netto(sub_total_price) =  18,69
Gesamt(total_price) =  19,99
total_credit =  19,99
total_credit(PayPal) =  19,99
total_credit =  19,99
{'gt_parse': {'menu': [{'nm': 'Pan VEGAN Curry', 'cnt': '1', 'price': '7,69', 'etc': '25'}, {'nm': 'Pan Margherita', 'cnt': '1', 'price': '6,15', 'etc': '25'}, {'nm': 'Pan Margherita', 'cnt': '1', 'price': '6,15', 'etc': '25'}], 'sub_total': {'subtotal_price': '18,69'}, 'total': {'total_price': '19,99', 'creditcardprice': '19,99'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 88, 'image_size': {'width': 1280, 'height': 1156}}, 'valid_line': [{'words': [{'quad': {'x1': 188, 'y1': 281, 'x2': 284, 'y2': 278, 'x3': 287, 'y3': 338, 'x4': 194, 'y4': 335}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 295, 'y1': 281, 'x2': 445, 'y2': 281, 'x3': 445, 'y3': 338, 'x4': 300, 'y4': 338}, 'is_key': 0, 'row_id': '1', 'text': 'VEGAN'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 456, 'y1': 286, 'x2': 598, 'y2': 286, 'x3': 598, 'y3': 349, 'x4': 461, 'y4': 349}, 'is_key': 0, 'row_id': '1', 'text': 'Curry'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 186, 'y1': 436, 'x2': 270, 'y2': 439, 'x3': 276, 'y3': 496, 'x4': 180, 'y4': 496}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 292, 'y1': 436, 'x2': 565, 'y2': 439, 'x3': 568, 'y3': 507, 'x4': 292, 'y4': 502}, 'is_key': 0, 'row_id': '2', 'text': 'Margherita'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 177, 'y1': 594, 'x2': 265, 'y2': 600, 'x3': 267, 'y3': 663, 'x4': 172, 'y4': 657}, 'is_key': 0, 'row_id': '3', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 287, 'y1': 603, 'x2': 559, 'y2': 597, 'x3': 559, 'y3': 668, 'x4': 284, 'y4': 663}, 'is_key': 0, 'row_id': '3', 'text': 'Margherita'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 57, 'y1': 270, 'x2': 101, 'y2': 275, 'x3': 101, 'y3': 333, 'x4': 57, 'y4': 335}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 958, 'y1': 502, 'x2': 1075, 'y2': 504, 'x3': 1086, 'y3': 447, 'x4': 955, 'y4': 444}, 'is_key': 0, 'row_id': '2', 'text': '6,15'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 112, 'y1': 273, 'x2': 175, 'y2': 273, 'x3': 180, 'y3': 335, 'x4': 112, 'y4': 335}, 'is_key': 0, 'row_id': '1', 'text': '25'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 30, 'y1': 804, 'x2': 177, 'y2': 804, 'x3': 172, 'y3': 875, 'x4': 16, 'y4': 870}, 'is_key': 0, 'row_id': '4', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 19, 'y1': 870, 'x2': 202, 'y2': 878, 'x3': 194, 'y3': 941, 'x4': 14, 'y4': 941}, 'is_key': 0, 'row_id': '5', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 961, 'y1': 954, 'x2': 1114, 'y2': 954, 'x3': 1122, 'y3': 886, 'x4': 958, 'y4': 883}, 'is_key': 0, 'row_id': '5', 'text': '19,99'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 11, 'y1': 1071, 'x2': 188, 'y2': 1063, 'x3': 194, 'y3': 987, 'x4': 8, 'y4': 987}, 'is_key': 0, 'row_id': '6', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 966, 'y1': 998, 'x2': 1114, 'y2': 1001, 'x3': 1119, 'y3': 1061, 'x4': 963, 'y4': 1071}, 'is_key': 0, 'row_id': '6', 'text': '19,99'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 1280, 'y2': 0, 'x3': 1280, 'y3': 1156, 'x4': 0, 'y4': 1156}}
89:
name =  Pan
name =  Salami
name =  Pizza-Br
name =  Salami
name =  Chicken
name =  Box
name =  Salat
name =  Green

95:
name =  Pan
name =  Salami
name =  Pan
name =  Spicy
name =  Salami
name =  Pan
name =  Salami
name =  Pan
name =  Lunch
name =  Champ
name =  Zwiebeln
count =  1
6,99
price =  6,99
size =  25
Netto(sub_total_price) =  38,75
Gesamt(total_price) =  41,46
total_credit =  41,46
total_credit(PayPal) =  41,46
total_credit =  41,46
{'gt_parse': {'menu': [{'nm': 'Pan Salami', 'cnt': '1', 'price': '11,99', 'etc': '28'}, {'nm': 'Pan Spicy Salami', 'cnt': '1', 'price': '11,99', 'etc': '28'}, {'nm': 'Pan Salami', 'cnt': '1', 'price': '10,49', 'etc': '25'}, {'nm': 'Pan Lunch Champ Zwiebeln', 'cnt': '1', 'price': '6,99', 'etc': '25'}], 'sub_total': {'subtotal_price': '38,75'}, 'total': {'total_price': '41,46', 'creditcardprice': '41,46'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 95, 'image_size': {'width': 567, 'height': 469}}, 'valid_line': [{'words': [{'quad': {'x1': 87, 'y1': 130, 'x2': 127, 'y2': 129, 'x3': 128, 'y3': 160, 'x4': 87, 'y4': 163}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 135, 'y1': 133, 'x2': 211, 'y2': 131, 'x3': 211, 'y3': 160, 'x4': 135, 'y4': 163}, 'is_key': 0, 'row_id': '1', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 84, 'y1': 184, 'x2': 125, 'y2': 184, 'x3': 129, 'y3': 210, 'x4': 84, 'y4': 210}, 'is_key': 0, 'row_id': '2', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 131, 'y1': 182, 'x2': 199, 'y2': 181, 'x3': 201, 'y3': 211, 'x4': 134, 'y4': 210}, 'is_key': 0, 'row_id': '2', 'text': 'Spicy'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 205, 'y1': 182, 'x2': 287, 'y2': 178, 'x3': 286, 'y3': 210, 'x4': 206, 'y4': 213}, 'is_key': 0, 'row_id': '2', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 84, 'y1': 230, 'x2': 127, 'y2': 235, 'x3': 124, 'y3': 257, 'x4': 86, 'y4': 254}, 'is_key': 0, 'row_id': '3', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 133, 'y1': 230, 'x2': 211, 'y2': 228, 'x3': 210, 'y3': 256, 'x4': 133, 'y4': 258}, 'is_key': 0, 'row_id': '3', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 84, 'y1': 277, 'x2': 123, 'y2': 277, 'x3': 124, 'y3': 305, 'x4': 84, 'y4': 306}, 'is_key': 0, 'row_id': '4', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 133, 'y1': 277, 'x2': 197, 'y2': 277, 'x3': 198, 'y3': 306, 'x4': 131, 'y4': 307}, 'is_key': 0, 'row_id': '4', 'text': 'Lunch'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 205, 'y1': 277, 'x2': 267, 'y2': 277, 'x3': 269, 'y3': 306, 'x4': 206, 'y4': 305}, 'is_key': 0, 'row_id': '4', 'text': 'Champ'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 288, 'y1': 272, 'x2': 387, 'y2': 272, 'x3': 388, 'y3': 301, 'x4': 288, 'y4': 304}, 'is_key': 0, 'row_id': '4', 'text': 'Zwiebeln'}], 'category': 'menu.nm', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 25, 'y1': 134, 'x2': 42, 'y2': 133, 'x3': 40, 'y3': 157, 'x4': 27, 'y4': 158}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 425, 'y1': 270, 'x2': 479, 'y2': 269, 'x3': 483, 'y3': 301, 'x4': 429, 'y4': 303}, 'is_key': 0, 'row_id': '4', 'text': '6,99'}], 'category': 'menu.price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 48, 'y1': 230, 'x2': 77, 'y2': 230, 'x3': 75, 'y3': 256, 'x4': 46, 'y4': 257}, 'is_key': 0, 'row_id': '3', 'text': '25'}], 'category': 'menu.etc', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 23, 'y1': 345, 'x2': 88, 'y2': 347, 'x3': 88, 'y3': 373, 'x4': 16, 'y4': 371}, 'is_key': 0, 'row_id': '5', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 19, 'y1': 398, 'x2': 103, 'y2': 400, 'x3': 100, 'y3': 374, 'x4': 19, 'y4': 374}, 'is_key': 0, 'row_id': '6', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 491, 'y1': 393, 'x2': 427, 'y2': 394, 'x3': 425, 'y3': 368, 'x4': 492, 'y4': 369}, 'is_key': 0, 'row_id': '6', 'text': '41,46'}], 'category': 'total.creditcardprice', 'group_id': '6', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 14, 'y1': 421, 'x2': 98, 'y2': 420, 'x3': 99, 'y3': 445, 'x4': 17, 'y4': 447}, 'is_key': 0, 'row_id': '7', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '7', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 427, 'y1': 409, 'x2': 490, 'y2': 408, 'x3': 492, 'y3': 436, 'x4': 426, 'y4': 438}, 'is_key': 0, 'row_id': '7', 'text': '41,46'}], 'category': 'total.creditcardprice', 'group_id': '7', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 567, 'y2': 0, 'x3': 567, 'y3': 469, 'x4': 0, 'y4': 469}}
96:
name =  Pan
name =  Caprese
name =  100ml
name =  BJ
name =  Cookie
name =  Dough
name =  500ml
name =  Coca
name =  Cola
count =  1
2,29
price =  2,29
Netto(sub_total_price) =  17,80
Gesamt(total_price) =  19,31
{'gt_parse': {'menu': [{'nm': 'Pan Caprese', 'cnt': '1', 'price': '13,78', 'etc': '28'}, {'nm': '100ml BJ Cookie Dough', 'cnt': '1', 'price': '2,99'}, {'nm': '500ml Coca Cola', 'cnt': '1', 'price': '2,29'}], 'sub_total': {'subtotal_price': '17,80'}, 'total': {'total_price': '19,31'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 96, 'image_size': {'width': 468, 'height': 346}}, 'valid_line': [{'words': [{'quad': {'x1': 65, 'y1': 117, 'x2': 96, 'y2': 116, 'x3': 100, 'y3': 140, 'x4': 67, 'y4': 142}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 104, 'y1': 118, 'x2': 174, 'y2': 120, 'x3': 177, 'y3': 142, 'x4': 106, 'y4': 143}, 'is_key': 0, 'row_id': '1', 'text': 'Caprese'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 36, 'y1': 176, 'x2': 85, 'y2': 175, 'x3': 87, 'y3': 196, 'x4': 36, 'y4': 197}, 'is_key': 0, 'row_id': '2', 'text': '100ml'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 95, 'y1': 176, 'x2': 118, 'y2': 178, 'x3': 119, 'y3': 195, 'x4': 95, 'y4': 196}, 'is_key': 0, 'row_id': '2', 'text': 'BJ'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 125, 'y1': 174, 'x2': 181, 'y2': 175, 'x3': 184, 'y3': 193, 'x4': 124, 'y4': 196}, 'is_key': 0, 'row_id': '2', 'text': 'Cookie'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 188, 'y1': 172, 'x2': 236, 'y2': 173, 'x3': 239, 'y3': 194, 'x4': 188, 'y4': 194}, 'is_key': 0, 'row_id': '2', 'text': 'Dough'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 32, 'y1': 217, 'x2': 90, 'y2': 218, 'x3': 89, 'y3': 195, 'x4': 32, 'y4': 196}, 'is_key': 0, 'row_id': '3', 'text': '500ml'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 93, 'y1': 193, 'x2': 137, 'y2': 197, 'x3': 136, 'y3': 217, 'x4': 95, 'y4': 216}, 'is_key': 0, 'row_id': '3', 'text': 'Coca'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 143, 'y1': 193, 'x2': 184, 'y2': 193, 'x3': 182, 'y3': 215, 'x4': 141, 'y4': 214}, 'is_key': 0, 'row_id': '3', 'text': 'Cola'}], 'category': 'menu.nm', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 13, 'y1': 118, 'x2': 29, 'y2': 118, 'x3': 31, 'y3': 139, 'x4': 12, 'y4': 139}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 335, 'y1': 216, 'x2': 389, 'y2': 216, 'x3': 389, 'y3': 196, 'x4': 338, 'y4': 194}, 'is_key': 0, 'row_id': '3', 'text': '2,29'}], 'category': 'menu.price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 15, 'y1': 254, 'x2': 67, 'y2': 249, 'x3': 70, 'y3': 272, 'x4': 14, 'y4': 275}, 'is_key': 0, 'row_id': '4', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 14, 'y1': 300, 'x2': 75, 'y2': 297, 'x3': 77, 'y3': 272, 'x4': 14, 'y4': 276}, 'is_key': 0, 'row_id': '5', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 468, 'y2': 0, 'x3': 468, 'y3': 346, 'x4': 0, 'y4': 346}}
97:
name =  Pan
name =  Chicken
name =  Spargel
name =  XL
name =  Chicken
count =  1
11,49
price =  11,49
Netto(sub_total_price) =  21,48
Gesamt(total_price) =  22,98
total_credit =  22,98
total_credit(PayPal) =  22,98
total_credit =  22,98
{'gt_parse': {'menu': [{'nm': 'Pan Chicken Spargel', 'cnt': '1', 'price': '11,49', 'etc': '28'}, {'nm': 'XL Chicken Kickers', 'cnt': '1', 'price': '11,49'}], 'sub_total': {'subtotal_price': '21,48'}, 'total': {'total_price': '22,98', 'creditcardprice': '22,98'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 97, 'image_size': {'width': 444, 'height': 285}}, 'valid_line': [{'words': [{'quad': {'x1': 64, 'y1': 101, 'x2': 96, 'y2': 102, 'x3': 94, 'y3': 125, 'x4': 65, 'y4': 123}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 166, 'y1': 102, 'x2': 102, 'y2': 101, 'x3': 102, 'y3': 126, 'x4': 166, 'y4': 126}, 'is_key': 0, 'row_id': '1', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 193, 'y1': 101, 'x2': 259, 'y2': 102, 'x3': 258, 'y3': 129, 'x4': 193, 'y4': 129}, 'is_key': 0, 'row_id': '1', 'text': 'Spargel'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 56, 'y1': 159, 'x2': 77, 'y2': 160, 'x3': 77, 'y3': 139, 'x4': 56, 'y4': 138}, 'is_key': 0, 'row_id': '2', 'text': 'XL'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 83, 'y1': 161, 'x2': 148, 'y2': 163, 'x3': 150, 'y3': 140, 'x4': 80, 'y4': 138}, 'is_key': 0, 'row_id': '2', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 21, 'y1': 104, 'x2': 32, 'y2': 103, 'x3': 32, 'y3': 120, 'x4': 22, 'y4': 122}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 322, 'y1': 105, 'x2': 373, 'y2': 104, 'x3': 373, 'y3': 129, 'x4': 322, 'y4': 131}, 'is_key': 0, 'row_id': '1', 'text': '11,49'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 18, 'y1': 171, 'x2': 69, 'y2': 170, 'x3': 69, 'y3': 193, 'x4': 17, 'y4': 192}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 77, 'y1': 212, 'x2': 17, 'y2': 210, 'x3': 18, 'y3': 191, 'x4': 76, 'y4': 192}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 382, 'y1': 225, 'x2': 326, 'y2': 223, 'x3': 327, 'y3': 198, 'x4': 384, 'y4': 202}, 'is_key': 0, 'row_id': '4', 'text': '22,98'}], 'category': 'total.creditcardprice', 'group_id': '4', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 14, 'y1': 249, 'x2': 75, 'y2': 251, 'x3': 73, 'y3': 227, 'x4': 16, 'y4': 224}, 'is_key': 0, 'row_id': '5', 'text': 'PayPal'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 328, 'y1': 234, 'x2': 381, 'y2': 237, 'x3': 380, 'y3': 260, 'x4': 329, 'y4': 260}, 'is_key': 0, 'row_id': '5', 'text': '22,98'}], 'category': 'total.creditcardprice', 'group_id': '5', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 444, 'y2': 0, 'x3': 444, 'y3': 285, 'x4': 0, 'y4': 285}}
98:
name =  Pan
name =  Lunch
name =  Individuell
name =  Chicken
name =  Strippers
count =  1
5,99
price =  5,99
Netto(sub_total_price) =  12,96
Gesamt(total_price) =  13,97
{'gt_parse': {'menu': [{'nm': 'Pan Lunch Individuell', 'cnt': '1', 'price': '6,99', 'etc': '25'}, {'nm': 'Chicken Strippers', 'cnt': '1', 'price': '5,99'}], 'sub_total': {'subtotal_price': '12,96'}, 'total': {'total_price': '13,97'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 98, 'image_size': {'width': 528, 'height': 393}}, 'valid_line': [{'words': [{'quad': {'x1': 87, 'y1': 125, 'x2': 124, 'y2': 127, 'x3': 122, 'y3': 153, 'x4': 88, 'y4': 153}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 129, 'y1': 127, 'x2': 189, 'y2': 129, 'x3': 188, 'y3': 152, 'x4': 128, 'y4': 152}, 'is_key': 0, 'row_id': '1', 'text': 'Lunch'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 195, 'y1': 127, 'x2': 316, 'y2': 129, 'x3': 317, 'y3': 158, 'x4': 195, 'y4': 154}, 'is_key': 0, 'row_id': '1', 'text': 'Individuell'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 72, 'y1': 211, 'x2': 154, 'y2': 212, 'x3': 153, 'y3': 238, 'x4': 73, 'y4': 235}, 'is_key': 0, 'row_id': '2', 'text': 'Chicken'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 161, 'y1': 212, 'x2': 261, 'y2': 214, 'x3': 262, 'y3': 240, 'x4': 160, 'y4': 237}, 'is_key': 0, 'row_id': '2', 'text': 'Strippers'}], 'category': 'menu.nm', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 30, 'y1': 126, 'x2': 47, 'y2': 125, 'x3': 47, 'y3': 147, 'x4': 34, 'y4': 148}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 397, 'y1': 214, 'x2': 445, 'y2': 213, 'x3': 445, 'y3': 243, 'x4': 397, 'y4': 243}, 'is_key': 0, 'row_id': '2', 'text': '5,99'}], 'category': 'menu.price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 92, 'y1': 280, 'x2': 25, 'y2': 277, 'x3': 25, 'y3': 298, 'x4': 94, 'y4': 300}, 'is_key': 0, 'row_id': '3', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 26, 'y1': 322, 'x2': 95, 'y2': 323, 'x3': 98, 'y3': 299, 'x4': 27, 'y4': 298}, 'is_key': 0, 'row_id': '4', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '4', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 528, 'y2': 0, 'x3': 528, 'y3': 393, 'x4': 0, 'y4': 393}}
99:
name =  Pan
name =  Lunch
name =  Broccoli
name =  Hollan
count =  2
14,78
price =  14,78
size =  25
Netto(sub_total_price) =  13,81
Gesamt(total_price) =  14,78
{'gt_parse': {'menu': [{'nm': 'Pan Lunch Broccoli Hollan', 'cnt': '2', 'price': '14,78', 'etc': '25'}], 'sub_total': {'subtotal_price': '13,81'}, 'total': {'total_price': '14,78'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 99, 'image_size': {'width': 448, 'height': 340}}, 'valid_line': [{'words': [{'quad': {'x1': 63, 'y1': 112, 'x2': 98, 'y2': 113, 'x3': 99, 'y3': 133, 'x4': 64, 'y4': 136}, 'is_key': 0, 'row_id': '1', 'text': 'Pan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 104, 'y1': 110, 'x2': 157, 'y2': 110, 'x3': 157, 'y3': 134, 'x4': 105, 'y4': 136}, 'is_key': 0, 'row_id': '1', 'text': 'Lunch'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 164, 'y1': 110, 'x2': 241, 'y2': 113, 'x3': 243, 'y3': 136, 'x4': 163, 'y4': 135}, 'is_key': 0, 'row_id': '1', 'text': 'Broccoli'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 250, 'y1': 112, 'x2': 315, 'y2': 116, 'x3': 314, 'y3': 142, 'x4': 250, 'y4': 138}, 'is_key': 0, 'row_id': '1', 'text': 'Hollan'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 8, 'y1': 111, 'x2': 26, 'y2': 111, 'x3': 24, 'y3': 134, 'x4': 9, 'y4': 135}, 'is_key': 0, 'row_id': '1', 'text': '2'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 340, 'y1': 118, 'x2': 393, 'y2': 120, 'x3': 392, 'y3': 145, 'x4': 338, 'y4': 141}, 'is_key': 0, 'row_id': '1', 'text': '14,78'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 33, 'y1': 110, 'x2': 55, 'y2': 110, 'x3': 56, 'y3': 134, 'x4': 34, 'y4': 136}, 'is_key': 0, 'row_id': '1', 'text': '25'}], 'category': 'menu.etc', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 7, 'y1': 228, 'x2': 67, 'y2': 227, 'x3': 67, 'y3': 246, 'x4': 7, 'y4': 248}, 'is_key': 0, 'row_id': '2', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 7, 'y1': 270, 'x2': 72, 'y2': 270, 'x3': 73, 'y3': 246, 'x4': 9, 'y4': 246}, 'is_key': 0, 'row_id': '3', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '3', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 448, 'y2': 0, 'x3': 448, 'y3': 340, 'x4': 0, 'y4': 340}}
9:
name =  Calzini
name =  Salami
count =  1
3,84
price =  3,84
Netto(sub_total_price) =  3,59
Gesamt(total_price) =  3,84
cashprice(Bar) =  3,84
{'gt_parse': {'menu': [{'nm': 'Calzini Salami', 'cnt': '1', 'price': '3,84'}], 'sub_total': {'subtotal_price': '3,59'}, 'total': {'total_price': '3,84', 'cashprice': '3,84'}}, 'meta': {'version': '2.0.0', 'split': 'train', 'image_id': 9, 'image_size': {'width': 809, 'height': 419}}, 'valid_line': [{'words': [{'quad': {'x1': 79, 'y1': 138, 'x2': 220, 'y2': 144, 'x3': 215, 'y3': 191, 'x4': 84, 'y4': 188}, 'is_key': 0, 'row_id': '1', 'text': 'Calzini'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 345, 'y1': 144, 'x2': 230, 'y2': 139, 'x3': 230, 'y3': 189, 'x4': 353, 'y4': 190}, 'is_key': 0, 'row_id': '1', 'text': 'Salami'}], 'category': 'menu.nm', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 40, 'y1': 138, 'x2': 8, 'y2': 137, 'x3': 4, 'y3': 183, 'x4': 39, 'y4': 178}, 'is_key': 0, 'row_id': '1', 'text': '1'}], 'category': 'menu.cnt', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 707, 'y1': 147, 'x2': 621, 'y2': 147, 'x3': 622, 'y3': 186, 'x4': 709, 'y4': 187}, 'is_key': 0, 'row_id': '1', 'text': '3,84'}], 'category': 'menu.price', 'group_id': '1', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 12, 'y1': 204, 'x2': 116, 'y2': 209, 'x3': 114, 'y3': 253, 'x4': 13, 'y4': 246}, 'is_key': 0, 'row_id': '2', 'text': 'Netto'}], 'category': 'subtotal.subtotal_price', 'group_id': '2', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 134, 'y1': 287, 'x2': 13, 'y2': 280, 'x3': 10, 'y3': 246, 'x4': 135, 'y4': 251}, 'is_key': 0, 'row_id': '3', 'text': 'Gesamt'}], 'category': 'total.total_price', 'group_id': '3', 'sub_group_id': 0}, {'words': [{'quad': {'x1': 729, 'y1': 290, 'x2': 634, 'y2': 289, 'x3': 635, 'y3': 254, 'x4': 731, 'y4': 253}, 'is_key': 0, 'row_id': '3', 'text': '3,84'}], 'category': 'total.cashprice', 'group_id': '3', 'sub_group_id': 0}], 'ROI': {'x1': 0, 'y1': 0, 'x2': 809, 'y2': 0, 'x3': 809, 'y3': 419, 'x4': 0, 'y4': 419}}

{'id': 9,
 'data': {'ocr': '/data/upload/5/085794fc-9.jpg'},
 'annotations': [{'id': 15,
   'created_username': ' ahmadbaratkhooei@gmail.com, 1',
   'created_ago': '2 weeks, 3 days',
   'completed_by': {'id': 1,
    'first_name': '',
    'last_name': '',
    'avatar': None,
    'email': 'ahmadbaratkhooei@gmail.com',
    'initials': 'ah'},
   'result': [{'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[4.945598417408506, 32.82442748091603],
       [0.9891196834817015, 32.63358778625954],
       [0.49455984174085077, 43.70229007633587],
       [4.8466864490603365, 42.55725190839694]],
      'closed': True},
     'id': 'qVQ7EeSGYb',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[40, 138], [8, 137], [4, 183], [39, 178]],
      'closed': True,
      'text': ['1']},
     'id': 'qVQ7EeSGYb',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[40, 138], [8, 137], [4, 183], [39, 178]],
      'closed': True,
      'text': ['1']},
     'id': 'qVQ7EeSGYb',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[9.79228486646884, 32.82442748091603],
       [27.20079129574679, 34.35114503816794],
       [26.607319485657765, 45.610687022900755],
       [10.385756676557866, 44.847328244274806]],
      'closed': True},
     'id': 'QkCvUIMRNm',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[79, 138], [220, 144], [215, 191], [84, 188]],
      'closed': True,
      'text': ['Calzini']},
     'id': 'QkCvUIMRNm',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[79, 138], [220, 144], [215, 191], [84, 188]],
      'closed': True,
      'text': ['1']},
     'id': 'QkCvUIMRNm',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[42.63105835806131, 34.35114503816794],
       [28.486646884272997, 33.20610687022901],
       [28.387734915924828, 45.038167938931295],
       [43.62017804154303, 45.229007633587784]],
      'closed': True},
     'id': 'uFGsgijkes',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[345, 144], [230, 139], [230, 189], [353, 190]],
      'closed': True,
      'text': ['Salami']},
     'id': 'uFGsgijkes',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[345, 144], [230, 139], [230, 189], [353, 190]],
      'closed': True,
      'text': ['1']},
     'id': 'uFGsgijkes',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[87.4381800197824, 35.11450381679389],
       [76.75568743818002, 35.11450381679389],
       [76.8545994065282, 44.465648854961835],
       [87.63600395647872, 44.65648854961833]],
      'closed': True},
     'id': 'Kjfbf55uXO',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[707, 147], [621, 147], [622, 186], [709, 187]],
      'closed': True,
      'text': ['3,84']},
     'id': 'Kjfbf55uXO',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[707, 147], [621, 147], [622, 186], [709, 187]],
      'closed': True,
      'text': ['1']},
     'id': 'Kjfbf55uXO',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[1.483679525222552, 48.66412213740459],
       [14.342235410484669, 49.80916030534351],
       [14.144411473788326, 60.30534351145038],
       [1.582591493570722, 58.77862595419849]],
      'closed': True},
     'id': '8eOrPg_aKd',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[12, 204], [116, 209], [114, 253], [13, 246]],
      'closed': True,
      'text': ['Netto']},
     'id': '8eOrPg_aKd',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[12, 204], [116, 209], [114, 253], [13, 246]],
      'closed': True,
      'text': ['2']},
     'id': '8eOrPg_aKd',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[89.41641938674579, 51.33587786259545],
       [79.03066271018793, 51.5267175572519],
       [79.03066271018793, 61.06870229007634],
       [90.70227497527202, 60.114503816793906]],
      'closed': True},
     'id': '_9rbh5OlAE',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[723, 215], [639, 216], [639, 256], [734, 252]],
      'closed': True,
      'text': ['3,59']},
     'id': '_9rbh5OlAE',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[723, 215], [639, 216], [639, 256], [734, 252]],
      'closed': True,
      'text': ['2']},
     'id': '_9rbh5OlAE',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[16.617210682492587, 68.51145038167938],
       [1.582591493570722, 66.79389312977099],
       [1.2858555885262117, 58.77862595419849],
       [16.716122650840752, 59.92366412213741]],
      'closed': True},
     'id': 'wknEQX3ZVa',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[134, 287], [13, 280], [10, 246], [135, 251]],
      'closed': True,
      'text': ['Gesamt']},
     'id': 'wknEQX3ZVa',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[134, 287], [13, 280], [10, 246], [135, 251]],
      'closed': True,
      'text': ['3']},
     'id': 'wknEQX3ZVa',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[90.10880316518298, 69.27480916030531],
       [78.33827893175072, 68.89312977099237],
       [78.5361028684471, 60.68702290076336],
       [90.40553907022749, 60.49618320610686]],
      'closed': True},
     'id': '4ANR2RBCGy',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[729, 290], [634, 289], [635, 254], [731, 253]],
      'closed': True,
      'text': ['3,84']},
     'id': '4ANR2RBCGy',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[729, 290], [634, 289], [635, 254], [731, 253]],
      'closed': True,
      'text': ['3']},
     'id': '4ANR2RBCGy',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[10.385756676557866, 76.5267175572519],
       [1.3847675568743818, 74.80916030534351],
       [1.1869436201780417, 85.30534351145039],
       [9.099901088031652, 85.11450381679388]],
      'closed': True},
     'id': 'zluDoUHSBj',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[84, 321], [11, 313], [10, 357], [74, 357]],
      'closed': True,
      'text': ['Bar']},
     'id': 'zluDoUHSBj',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[84, 321], [11, 313], [10, 357], [74, 357]],
      'closed': True,
      'text': ['4']},
     'id': 'zluDoUHSBj',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[88.85423605644039, 75.38167938931298],
       [77.2502472799209, 76.14503816793892],
       [76.99514523910456, 87.46662655586056],
       [88.82294757665676, 86.6412213740458]],
      'closed': True},
     'id': '25nAoG79YT',
     'from_name': 'poly',
     'to_name': 'image',
     'type': 'polygon',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[719, 316], [625, 319], [623, 366], [719, 363]],
      'closed': True,
      'text': ['3,84']},
     'id': '25nAoG79YT',
     'from_name': 'transcription',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'},
    {'original_width': 809,
     'original_height': 419,
     'image_rotation': 0,
     'value': {'points': [[719, 316], [625, 319], [623, 366], [719, 363]],
      'closed': True,
      'text': ['4']},
     'id': '25nAoG79YT',
     'from_name': 'Line',
     'to_name': 'image',
     'type': 'textarea',
     'origin': 'manual'}],
   'was_cancelled': False,
   'ground_truth': False,
   'created_at': '2023-05-27T10:00:20.427613Z',
   'updated_at': '2023-06-13T21:26:58.185591Z',
   'lead_time': 321.179,
   'last_action': None,
   'task': 16,
   'project': 5,
   'updated_by': 1,
   'parent_prediction': None,
   'parent_annotation': None,
   'last_created_by': None}],
 'predictions': []}